(function(g){var window=this;'use strict';var CT=function(v){v.isActive()||v.start()},av=function(v){var q={languageCode:v.languageCode,
languageName:v.languageName,displayName:g.Jm(v),kind:v.kind,name:v.name,id:v.id,is_servable:v.D,is_default:v.isDefault,is_translateable:v.isTranslateable,vss_id:v.vssId};v.xtags&&(q.xtags=v.xtags);v.captionId&&(q.captionId=v.captionId);v.translationLanguage&&(q.translationLanguage=v.translationLanguage);return q},F1O=function(v,q){var x=new g.yi;
x.languageCode=v.languageCode;x.languageName=v.languageName;x.name=v.name;x.displayName=v.displayName;x.kind=v.kind;x.isDefault=!1;x.D=v.D;x.isTranslateable=v.isTranslateable;x.vssId=v.vssId;x.url=v.url;x.translationLanguage=q;v.xtags&&(x.xtags=v.xtags);v.captionId&&(x.captionId=v.captionId);return x},Si=function(v,q){return q?v.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},vGs=function(v){return g.b6(v)||v.N("web_enable_caption_language_preference_stickiness")},s3x=async function(v,q){v=
v+"|"+q;
q=await g.oc();if(!q)throw g.cw("gct");return(await g.tG(q)).get("captions",v)},q7g=function(v,q,x){s3x(v,q).then(X=>{X&&x(X.trackData,new g.yi(X.metadata))})},WQ=function(v){if(!xyy.test(v))throw Error("'"+v+"' is not a valid hex color");
v.length==4&&(v=v.replace(Xog,"#$1$1$2$2$3$3"));v=v.toLowerCase();v=parseInt(v.slice(1),16);return[v>>16,v>>8&255,v&255]},iHr=function(){var v={},q="suggest_correction"in g.aA?g.aA.suggest_correction:"Edit caption";
q=q||"";for(let x in v){let X=()=>String(v[x]);
q=q.replace(new RegExp("\\$\\{"+x+"\\}","gi"),X);q=q.replace(new RegExp("\\$"+x,"gi"),X)}return q},Iv=function(){return g.zQ("yt-player-caption-display-settings")},yH2=function(v,q){g.HB(q,x=>v.equals(x))||q.push(v)},bw=function(v,q){switch(q.kind){case "asr":yH2(q,v.O);
break;default:yH2(q,v.X)}},ZHg=async function(v,q,x){v.X=g.Sw(q,x)},JH2=function(v,q){var x=g.xY(v.segments,q);
x>=0||x<0&&(-x-1)%2===1||(x=-x-1,x>0&&q-v.segments[x-1]===1&&x<v.segments.length&&v.segments[x]-q===1?(g.PB(v.segments,x),g.PB(v.segments,x-1)):x>0&&q-v.segments[x-1]===1?v.segments[x-1]=q:x<v.segments.length&&v.segments[x]-q===1?v.segments[x]=q:(g.vV(v.segments,x,0,q),g.vV(v.segments,x+1,0,q)))},gG2=function(v){return v.D&&v.D.C?v.D.C+v.player.F4()<v.player.getCurrentTime():!1},oGO=function(v,q){if(v.policy.VZ&&v.player.NK()){var x=g.Ub(q,v.policy,{});
x.set("pot",v.player.NK());x=x.FQ()}else x=g.Ub(q,v.policy,{}).FQ();var X={format:"RAW",withCredentials:!0};if(v.policy.gO){X.method="POST";let J=q.j;J&&Object.keys(J).length>0?X.postBody=g.P8(J,g.jj):X.postBody=(0,g.yb)([120,0])}v.C&&(X.responseType="arraybuffer");var y=++v.hk,Z=(0,g.O)();v.X=g.Qu(x,X,3,100,-1,J=>{J.errorCode==="net.timeout"&&v.player.W("capnt",{rn:y++})}).then(J=>{if(v.policy.ya&&y%100===1){var M=(0,g.O)();
v.player.W("caprsp",{rn:y,ms:M-Z,kb:(J.xhr.responseText.length/1024).toFixed()})}a:{J=J.xhr;v.Ck();if(v.O){var l=!(v.C?J.response:J.responseText)||J.status>=400;if(M=g.gC(J)){J=g.Ub(v.O,v.policy,{});v.O.oe(J,M);oGO(v,v.O);break a}l?v.player.W("capfail",{status:J.status}):(g.Ao("fcb_r",(0,g.O)(),v.player.getVideoData().Xm||""),M=v.O.VY[0],l=M.Kk,v.Y!=null&&v.L!==l&&(v.C?v.Y(J.response,(M.segmentStartTime+v.player.F4())*1E3):v.Y(J.responseText,(M.segmentStartTime+v.player.F4())*1E3),v.L=l))}v.O=null;
v.X=null}}).eN(J=>{v.O=null;
v.X=null;v.player.W("capfail",{rn:y,status:J.xhr?.status})});
v.O=q;JH2(v.j,v.O.VY[0].Kk)},j32=function(v,q){return q!=null&&q in v.X.D?v.X.D[q]:null},MSB=function(v,q,x){var X=[];
for(let y in v.X.D){if(!v.X.D.hasOwnProperty(y))continue;let Z=v.X.D[y];if(g.D1(Z,x||null)){let J=Z.info.captionTrack;J&&J.languageCode===q&&X.push(Z)}}return X.length?X[0]:null},lj7=function(v,q){var x=[];
for(let y in v.X.D){if(!v.X.D.hasOwnProperty(y))continue;var X=v.X.D[y];if(g.D1(X,q||null)){let Z=X.info.id,J=Z,M=`.${Z}`,l="",B="";if(X=X.info.captionTrack)Z=X.languageCode,J=X.displayName,M=X.vssId,l=X.kind,B=X.id;x.push(new g.yi({id:y,languageCode:Z,languageName:J,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:M,kind:l,captionId:B}))}}return x},pT=function(v){if(typeof DOMParser!="undefined")return g.Mx(new DOMParser,g.DQ(v),"application/xml");
throw Error("Your browser does not support loading xml documents");},Gpg=function(v,q,x,X){var y=q/360*16;
q>=v&&(v=640,X>x*1.3&&(v=480),y=x/v*16);return y},AH6=function(v){var q=1+.25*(v.fontSizeIncrement||0);
if(v.offset===0||v.offset===2)q*=.8;return q},NcB=function(v,q){var x="vertical-rl";
v.D.VE===1&&(x="vertical-lr");g.ZT&&(x=x==="vertical-lr"?"tb-lr":"tb-rl");g.Ji(q,"-o-writing-mode",x);g.Ji(q,"-webkit-writing-mode",x);g.Ji(q,"writing-mode",x);g.Ji(q,"text-orientation","upright");g.hy(q,"ytp-vertical-caption");v.O.params.Xg===3&&(g.Ji(q,"text-orientation",""),g.Ji(q,"transform","rotate(180deg)"))},Bc_=function(v,q){var x={},X=q.background?q.background:v.D.pW.background;
if(q.backgroundOpacity!=null||q.background){var y=q.backgroundOpacity!=null?q.backgroundOpacity:v.D.pW.backgroundOpacity;X=WQ(X);x.background="rgba("+X[0]+","+X[1]+","+X[2]+","+y+")";v.Jk&&(x["box-decoration-break"]="clone",x["border-radius"]=`${v.Z3*.25}px`)}if(q.fontSizeIncrement!=null||q.offset!=null)x["font-size"]=`${v.G4*AH6(q)}px`;v.experiments.M4("enable_player_captions_new_style_defaults")&&(x["line-height"]="1.375");X=1;y=q.color||v.D.pW.color;if(q.color||q.textOpacity!=null)y=WQ(y),X=q.textOpacity==
null?v.D.pW.textOpacity:q.textOpacity,y="rgba("+y[0]+","+y[1]+","+y[2]+","+X+")",x.color=y,x.fill=y;var Z=q.charEdgeStyle;Z===0&&(Z=void 0);if(Z){y=`rgba(34, 34, 34, ${X})`;let l=`rgba(204, 204, 204, ${X})`;q.kL&&(l=y=q.kL);let B=v.G4/16/2,a=Math.max(B,1);var J=Math.max(2*B,1),M=Math.max(3*B,1);let S=Math.max(5*B,1);X=[];switch(Z){case 4:for(;M<=S;M+=B)X.push(`${J}px ${J}px ${M}px ${y}`);break;case 1:J=window.devicePixelRatio>=2?.5:1;for(Z=a;Z<=M;Z+=J)X.push(`${Z}px ${Z}px ${y}`);break;case 2:X.push(`${a}px ${a}px ${l}`);
X.push(`-${a}px -${a}px ${y}`);break;case 3:for(M=0;M<5;M++)X.push(`0 0 ${J}px ${y}`)}x["text-shadow"]=X.join(", ")}y="";switch(q.fontFamily){case 1:y='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", serif-monospace, monospace';break;case 2:y='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:y='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", sans-serif-monospace, monospace';break;case 5:y='"Comic Sans MS", Impact, Handlee, fantasy';break;
case 6:y='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:y=g.TT()?'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:y='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}y&&(x["font-family"]=y);y=q.offset;y==null&&(y=v.D.pW.offset);switch(y){case 0:x["vertical-align"]="sub";break;case 2:x["vertical-align"]="super"}q.fontFamily===7&&(x["font-variant"]=
"small-caps");q.bold&&(x["font-weight"]="bold");q.italic&&(x["font-style"]="italic");q.underline&&(x["text-decoration"]="underline");q.t0&&(x.visibility="hidden");q.SO===1&&v.L&&(x["text-combine-upright"]="all",x["text-orientation"]="mixed",y=g.Qp||g.bA,v.O.params.Xg===3?x.transform=y?"rotate(90deg)":"rotate(180deg)":y&&(x.transform="rotate(-90deg)"));if(q.textEmphasis===1||q.textEmphasis===2||q.textEmphasis===3||q.textEmphasis===4||q.textEmphasis===5)if(g.Qp)x["font-weight"]="bold";else switch(x["text-emphasis-style"]=
"filled circle",x["text-emphasis-color"]="currentcolor",x["webkit-text-emphasis"]="filled circle",q.textEmphasis){case 4:case 3:x["text-emphasis-position"]="under left";x["webkit-text-emphasis-position"]="under left";break;case 5:case 2:x["text-emphasis-position"]="over right",x["webkit-text-emphasis-position"]="over right"}return x},Csy=function(v,q){if(v.Ok&&q.length===0)return 0;
v=1;for(let x=0;x<q.length;x++){let X=q[x];typeof X.text==="string"&&(v+=X.text.split("\n").length-1,X.append||x===0||v++)}return v},YF=function(v){v=v.split("px");
return v.length>0?(v=Number(v[0]))?v:0:0},Wf6=function(v,q,x){v.BA=v.BA||!!x;
var X={};Object.assign(X,v.D.pW);Object.assign(X,x||q.D);Object.assign(X,v.uI.pW);v.cA&&(X.backgroundOpacity=0);(x=!v.K)&&ajB(v);var y=v.Rm&&v.vA&&g.Ap(X,v.vA)?v.Rm:S7T(v,X),Z=typeof q.text==="string",J=Z?q.text.split("\n"):[q.text];for(let l=0;l<J.length;l++){var M=l>0||!q.append;let B=J[l];M&&!x?(ajB(v),y=S7T(v,X)):M&&x&&(x=!1);B&&(y.appendChild(Z?g.Oz(B):B),Z||B.tagName!=="RUBY"||B.childElementCount!==4||g.Qp||!g.M0(B.children[2],"text-emphasis")||(M=v.L?"padding-right":"padding-top",g.M0(B.children[2],
"text-emphasis-position")&&(M=v.L?"padding-left":"padding-bottom"),g.mR?g.Ji(y,M,"1em"):g.Ji(y,M,"0.5em")))}v.vA=X;v.Rm=y;v.G.push(q)},ajB=function(v){if(v.K){var q=v.K;
if(v.Jk){var x=v.D.textAlign;x===0?(q=q.firstElementChild)&&g.Ji(q,{"border-bottom-left-radius":"0"}):x===1&&(q=q.lastElementChild)&&g.Ji(q,{"border-bottom-right-radius":"0"})}}v.K=g.K1("SPAN");g.Ji(v.K,{display:"block"});g.hy(v.K,"caption-visual-line");v.C.appendChild(v.K)},S7T=function(v,q){var x=g.K1("SPAN");
g.Ji(x,{display:"inline-block","white-space":"pre-wrap"});g.Ji(x,Bc_(v,q));x.classList.add("ytp-caption-segment");v.K.appendChild(x);v.Jk&&v.C.children.length>1&&(v=v.D.textAlign,v===0?x.previousElementSibling||g.Ji(x,{"border-top-left-radius":"0"}):v===1&&g.Ji(x,{"border-top-right-radius":"0"}));x.previousElementSibling&&(g.Ji(x.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Ji(x,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return x},
bHr=function(v,q,x){if(v===255&&q===255||!v&&!q)return{TO:v,
wb:q,result:0};v=Ijr[v];q=Ijr[q];if(v&128){var X;if(X=!(q&128))X=q,X=x.cG()&&x.wb===X;if(X)return{TO:v,wb:q,result:1}}else if(q&128&&1<=v&&v<=31)return{TO:v,wb:q,result:2};return{TO:v,wb:q,result:3}},Y7K=function(v,q,x,X){q===255&&x===255||!q&&!x?(++v.O===45&&v.reset(),v.j.X.clear(),v.C.X.clear()):(v.O=0,poK(v.j,q,x,X))},cHT=function(v,q){v.D.sort((x,X)=>{var y=x.time-X.time;
return y===0?x.order-X.order:y});
for(let x of v.D)v.time=x.time,x.type===0?Y7K(v,x.QC,x.jv,q):x.type===1&&v.X&496&&poK(v.C,x.QC,x.jv,q);v.D.length=0},wo2=function(v,q){switch(v){case 0:return eAs[(q&127)-32];
case 1:return tSO[q&15];case 2:return VS7[q&31];case 3:return Q3_[q&31]}return 0},cQ=function(v,q){if(v.style.type===3){var x=0,X=0,y=v.C.time+0,Z="",J="",M=y;
for(var l=1;l<=15;++l){var B=!1;for(var a=X?X:1;a<=32;++a){var S=v.O[l][a];if(S.D!==0){x===0&&(x=l,X=a);B=String.fromCharCode(S.D);var I=S.timestamp;I<y&&(y=I);S.timestamp=M;J&&(Z+=J,J="");Z+=B;B=!0}if((S.D===0||a===32)&&B){J="\n";break}else if(X&&!B)break}if(x&&!B)break}Z&&q.j(x,X,y,M,Z)}else for(X=x=0,Z=y=v.C.time+0,J=1;J<=15;++J)for(M="",l=1;l<=32;++l)if(a=v.O[J][l],S=a.D,S!==0&&(x===0&&(x=J,X=l),B=String.fromCharCode(S),I=a.timestamp,I<=y&&(y=I),M+=B,a.reset()),l===32||S===0)M&&q.j(x,X,y,Z,M),
y=Z,M="",X=x=0},ei=function(v){return v.O[v.row][v.X]},tC=function(v,q,x){q>=2&&v.X>1&&(--v.X,ei(v).D=0);
var X=ei(v);X.timestamp=v.C.time+0;X.D=wo2(q,x);v.X<32&&v.X++},hAK=function(v,q,x,X){for(let y=0;y<X;y++)for(let Z=0;Z<=32;Z++)v.O[q+y][Z].copy(v.O[x+y][Z])},Vg=function(v,q,x){for(let X=0;X<x;X++)for(let y=0;y<=32;y++)v.O[q+X][y].reset()},Qg=function(v){v.row=v.D>0?v.D:1;
v.X=1;Vg(v,0,15)},Dyr=function(v){v.style.set(1);
v.D=v.j;v.D.D=0;v.D.style=v.style;v.O.mode=1<<v.D.j},w0=function(v,q,x){var X=v.X,y=!1;
switch(v.style.get()){case 4:case 1:case 2:v.style.get()===4&&X.D>0||(cQ(X,x),Qg(v.X),Qg(v.j),X.row=15,X.D=q,y=!0)}v.style.set(3);v.D=X;v.D.style=v.style;v.O.mode=1<<X.j;y?X.X=1:X.D!==q&&(X.D>q?(cQ(X,x),Vg(X,X.row-X.D,q)):X.row<q&&(q=X.D),X.D=q)},Uyg=function(v){v.style.set(4);
v.D=v.text;v.D.style=v.style;v.O.mode=1<<v.D.j},poK=function(v,q,x,X){v.X.update();
q=bHr(q,x,v.X);switch(q.result){case 0:return;case 1:case 2:return}var y=q.TO;q=q.wb;if(32<=y||!y)v.D.mode&v.D.X&&(x=y,x&128&&(x=127),q&128&&(q=127),v=v.j.D,x&96&&tC(v,0,x),q&96&&tC(v,0,q),x!==0&&q!==0&&v.style.type===3&&cQ(v,X));else if(y&16)a:if(!v.X.matches(y,q)&&(x=v.X,x.TO=y,x.wb=q,x.state=2,x=y&8?v.L:v.O,v.j=x,v.D.mode=1<<(v.C<<2)+(x.C<<1)+(x.style.type===4?1:0),(v.D.mode|1<<(v.C<<2)+(x.C<<1)+(x.style.type!==4?1:0))&v.D.X))if(q&64){X=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(y&7)<<1|q>>5&1];
v=q&16?((q&14)>>1)*4:0;q=x.D;switch(x.style.get()){case 4:X=q.row;break;case 3:if(X!==q.row){if(X<q.D&&(X=q.D,X===q.row))break;var Z=1+q.row-q.D;let J=1+X-q.D;hAK(q,J,Z,q.D);x=Z;y=q.D;J<Z?(Z=J+y-Z,Z>0&&(x+=Z,y-=Z)):(Z=Z+y-J,Z>0&&(y-=Z));Vg(q,x,y)}}q.row=X;q.X=v+1}else switch(y&7){case 1:switch(q&112){case 32:tC(x.D,0,32);break a;case 48:q===57?(X=x.D,ei(X).D=0,X.X<32&&X.X++):tC(x.D,1,q&15)}break;case 2:q&32&&tC(x.D,2,q&31);break;case 3:q&32&&tC(x.D,3,q&31);break;case 4:case 5:if(32<=q&&q<=47)switch(q){case 32:Dyr(x);
break;case 33:X=x.D;X.X>1&&(--X.X,ei(X).D=0);break;case 36:X=x.D;v=ei(X);for(q=0;q<=15;q++)for(x=0;x<=32;x++)if(X.O[q][x]===v){for(;x<=32;x++)X.O[q][x].reset();break}break;case 37:w0(x,2,X);break;case 38:w0(x,3,X);break;case 39:w0(x,4,X);break;case 40:tC(x.D,0,32);break;case 41:X=x;X.style.set(2);X.D=X.X;X.D.D=0;X.D.style=X.style;X.O.mode=1<<X.D.j;break;case 42:X=x;v=X.text;v.D=15;v.style.set(4);Qg(v);Uyg(X);break;case 43:Uyg(x);break;case 44:v=x;q=v.X;switch(v.style.get()){case 1:case 2:case 3:cQ(q,
X)}Vg(q,0,15);break;case 45:b:{q=x;v=q.D;switch(q.style.get()){default:case 2:case 1:break b;case 4:if(v.row<15){++v.row;v.X=1;break b}break;case 3:}v.D<2&&(v.D=2,v.row<v.D&&(v.row=v.D));q=v.row-v.D+1;cQ(v,X);hAK(v,q,q+1,v.D-1);Vg(v,v.row,1)}break;case 46:Vg(x.j,0,15);break;case 47:v=x,cQ(v.X,X),v.j.updateTime(v.O.time+0),X=v.j,v.j=v.X,v.X=X,Dyr(v)}break;case 7:switch(q){case 33:case 34:case 35:X=x.D,(X.X+=q&3)>32&&(X.X=32)}}},nG6=function(v,q,x,X,y,Z,J){var M=Z[0],l=J[M.getAttribute("p")];
if(l.kv===1){var B=Z[1],a=Z[2];Z=Z[3];M.getAttribute("t");B.getAttribute("t");a.getAttribute("t");Z.getAttribute("t");M.getAttribute("p");B.getAttribute("p");Z.getAttribute("p");J=J[a.getAttribute("p")];M=myB(M.textContent,B.textContent,a.textContent,Z.textContent,J);return new hC(v,q,y,x,M,X,l)}switch(l.kv){case 9:case 10:l.textEmphasis=1;break;case 11:l.textEmphasis=2;break;case 12:l.textEmphasis=3;break;case 13:l.textEmphasis=4;break;case 14:l.textEmphasis=5}return new hC(v,q,y,x,M.textContent||
"",X,l)},myB=function(v,q,x,X,y){var Z=g.TT(),J=Z?g.K1("DIV"):g.K1("RUBY"),M=g.K1("SPAN");
M.textContent=v;J.appendChild(M);v=Z?g.K1("DIV"):g.K1("RP");v.textContent=q;J.appendChild(v);q=Z?g.K1("DIV"):g.K1("RT");q.textContent=x;J.appendChild(q);x=y.kv;if(x===10||x===11||x===12||x===13||x===14)if(g.Ji(q,"text-emphasis-style","filled circle"),g.Ji(q,"text-emphasis-color","currentcolor"),g.Ji(q,"webkit-text-emphasis","filled circle"),y.kv===11||y.kv===13)g.Ji(q,"webkit-text-emphasis-position","under left"),g.Ji(q,"text-emphasis-position","under left");x=!0;if(y.kv===4||y.kv===7||y.kv===12||
y.kv===14)g.Ji(J,"ruby-position","over"),g.Ji(J,"-webkit-ruby-position","before");else if(y.kv===5||y.kv===6||y.kv===11||y.kv===13)g.Ji(J,"ruby-position","under"),g.Ji(J,"-webkit-ruby-position","after"),x=!1;y=Z?g.K1("DIV"):g.K1("RP");y.textContent=X;J.appendChild(y);Z&&(X=x,g.Ji(J,{display:"inline-block",position:"relative"}),Z=J.firstElementChild.nextElementSibling,g.Ji(Z,"display","none"),Z=Z.nextElementSibling,g.Ji(Z,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.Ji(J.lastElementChild,"display","none"),X?(g.Ji(J,"padding-top","0.6em"),g.Ji(Z,"top","0")):(g.Ji(J,"padding-bottom","0.6em"),g.Ji(Z,"bottom","0")));return J},rHr=function(v){var q="_"+Do++;
return new Ur(0,0x8000000000000,0,q,v)},mt=function(v,q){v=v.getAttribute(q);
if(v!=null)return Number(v)},nT=function(v,q){v=v.getAttribute(q);
if(v!=null)return v==="1"},r0=function(v,q){v=mt(v,q);
return v!==void 0?v:null},kF=function(v,q){v=v.getAttribute(q);
if(v!=null)return fT.test(v),v},fj7=function(v,q){var x={},X=q.getAttribute("ws");
Object.assign(x,X?v.G[X]:v.j);v=r0(q,"mh");v!=null&&(x.zL=v);v=r0(q,"ju");v!=null&&(x.textAlign=v);v=r0(q,"pd");v!=null&&(x.Xg=v);v=r0(q,"sd");v!=null&&(x.VE=v);v=kF(q,"wfc");v!=null&&(x.windowColor=v);q=mt(q,"wfo");q!==void 0&&(x.windowOpacity=q/255);return x},kpK=function(v,q){var x={},X=q.getAttribute("wp");
X&&Object.assign(x,v.Y[X]);v=r0(q,"ap");v!=null&&(x.NS=v);v=mt(q,"cc");v!=null&&(x.jC=v);v=mt(q,"ah");v!=null&&(x.K1=v);v=mt(q,"rc");v!=null&&(x.U0=v);q=mt(q,"av");q!=null&&(x.V7=q);return x},RA6=function(v,q,x,X){var y={};
Object.assign(y,kpK(v,q));Object.assign(y,fj7(v,q));X?g.Ap(y,v.j)?(X=v.C,y=v.j):X="_"+Do++:X=q.getAttribute("id")||"_"+Do++;v=mt(q,"t")+x;q=mt(q,"d")||0x8000000000000;if(y.Xg===2||y.Xg===3)x=y.U0,y.U0=y.jC,y.jC=x;return new Ur(v,q,0,X,y)},Rv=function(v){v=g.O5(Math.round(v),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-v.length)+v},zAO=function(v,q,x,X,y){X===0&&(X=0x8000000000000);
var Z={};q.wpWinPosId&&Object.assign(Z,v.j.get(q.wpWinPosId));q.wsWinStyleId&&Object.assign(Z,v.C.get(q.wsWinStyleId));v=q.rcRowCount;v!==void 0&&(Z.U0=v);q=q.ccColCount;q!==void 0&&(Z.jC=q);if(Z.Xg===2||Z.Xg===3)q=Z.U0,Z.U0=Z.jC,Z.jC=q;return new Ur(x,X,0,y,Z)},z0=function(v){var q=v.byteOffset;
v.byteOffset+=1;return v.D.getUint8(q)},d0=function(v){var q=v.byteOffset;
v.byteOffset+=4;return v.D.getUint32(q)},KfB=function(v){if(typeof v==="string")return!1;
v=new dyK(v,0);return HHg(v)},HHg=function(v){if(!(v.byteOffset<v.D.byteLength)||d0(v)!==1380139777)return!1;
v.version=z0(v);if(v.version>1)return!1;z0(v);z0(v);z0(v);return!0},OHO=function(v,q){if(!q)return"";
v.L&&v.O.params.VE!==1&&(q*=-1);return`translate${v.L?"X":"Y"}(${q}px)`},$y6=function(v){v.rO=Array.from(v.element.getElementsByClassName("caption-visual-line"));
for(var q=v.O.params.U0,x=0,X=0,y=v.rO.length-1;x<q&&y>-1;){var Z=v.rO[y];X+=v.L?Z.offsetWidth:Z.offsetHeight;x++;y--}v.hk=X;q=Math;x=q.max;isNaN(v.gO)&&((X=v.D.jC)?(y=g.K1("SPAN"),g.Ez(y,"\u2013".repeat(X)),g.Ji(y,Bc_(v,v.D.pW)),v.C.appendChild(y),v.gO=y.offsetWidth,v.C.removeChild(y)):v.gO=0);X=v.C;q=x.call(q,v.gO,v.Bi,(v.L?X.offsetHeight:X.offsetWidth)+1);v.Av&&(q=Math.min(q,v.maxWidth));v.Oy=q},PsB=function(v,q){$y6(v);
var x=v.rO.reduce((X,y)=>(v.L?y.offsetWidth:y.offsetHeight)+X,0);
x=v.hk-x;if(x!==v.q4){let X=x>0&&v.q4===0,y=x<v.q4;q||isNaN(x)||X||!y||(g.hy(v.element,"ytp-rollup-mode"),v.D3(v.element,"transitionend",v.jb));g.Ji(v.C,"transform",OHO(v,x));v.q4=x}$y6(v)},Lf5=function(v,q,x,X){var {formatId:y,
Kk:Z,startTimeMs:J,durationMs:M}=v.K(q),l={formatId:y,startTimeMs:J,durationMs:M,XQ:Z,xt:Z},B=Tcr(v.fF,l.startTimeMs),a=B>=0?v.fF[B]:null,S=a?a.startTimeMs+a.durationMs:0,I=l.startTimeMs+l.durationMs;!a||l.startTimeMs-S>v.j?v.fF.splice(B+1,0,l):(a.durationMs=Math.max(S,I)-a.startTimeMs,a.xt=Math.max(a.xt,l.xt));X(v.fF);X=g.Eb(q);v=v.C;X=X.buffer.slice(X.byteOffset,X.byteLength+X.byteOffset);q=q.info.j;v.wO?v.Y==null?g.P7(v.logger,350058965,"Null loaded track meta data at captions data received"):
x.RO(X,v.Y,q*1E3):g.P7(v.logger,350058965,"Null Representation at captions data received")},Ffy=function(v,q){v.X=(x,X)=>{if(v.U.J().experiments.M4("html5_sabr_live_support_subfragmented_captions"))(v.D?v.D=v.D.merge(x):(v.D=x,EGy(v.D)),v.D)?x.info.VK&&(uly(v.D),Lf5(v,v.D,q,X),v.D=null):g.P7(v.logger,350058965,"Empty slice");
else if(x.info.VK){var y=x;if(v.HF.length>0){for(y=v.HF.shift();v.HF.length>0;)y=y?.merge(v.HF.shift());y=y?.merge(x)}y?(EGy(y),uly(y),Lf5(v,y,q,X)):g.P7(v.logger,350058965,"Empty slice")}else v.HF.push(x)};
v.U.addEventListener("sabrCaptionsDataLoaded",v.X)},Tcr=function(v,q){v=g.xY(v,{startTimeMs:q},(x,X)=>x.startTimeMs-X.startTimeMs);
return v>=0?v:-v-2},EGy=function(v){try{var q=g.sq(v)*1E3}catch(x){q=v.info.segmentStartTime*1E3}q<0&&(q=v.info.segmentStartTime*1E3);
v.info.segmentStartTime=q/1E3;v.info.j=q/1E3},uly=function(v){try{var q=g.ym(v)*1E3}catch(x){q=v.info.O*1E3}q<0&&(q=v.info.O*1E3);
v.info.O=q/1E3;v.info.K=q/1E3},v66=function(v,q){if(!g.T1(v)||v.D!=null&&g.h2(q,v.D)&&v.D.D.rawcc!=null)return!1;
q=!!v.D&&v.D.isManifestless&&Object.values(v.D.D).some(x=>g.D1(x,"386"));
v=!!v.D&&!v.D.isManifestless&&g.VD(v.D);return q||v},sB5=function(v,q,x){var X=[];
for(let y in v.X.D){if(!v.X.D.hasOwnProperty(y))continue;let Z=v.X.D[y];if(g.D1(Z,x||null)){let J=Z.info.captionTrack;J&&J.languageCode===q&&X.push(Z)}}return X.length?X[0]:null},qFK=function(v,q){var x=[];
for(let y in v.X.D){if(!v.X.D.hasOwnProperty(y))continue;var X=v.X.D[y];if(g.D1(X,q||null)){let Z=X.info.id,J=Z,M=`.${Z}`,l="",B="";if(X=X.info.captionTrack)Z=X.languageCode,J=X.displayName,M=X.vssId,l=X.kind,B=X.id;x.push(new g.yi({id:y,languageCode:Z,languageName:J,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:M,kind:l,captionId:B}))}}return x},X57=function(v){var q=xJg.length;
if(v.byteLength<q)return!1;v=new Uint8Array(v,0,q);for(let x=0;x<q;x++)if(xJg[x]!==v[x])return!1;return!0},HQ=function(v){v=v.split(":");
var q=0;for(let x of v)q=q*60+Number(x);return q*1E3},i$6=function(v,q,x,X){X=Object.assign({zL:0},X);
return new Ur(v,q,x,"_"+Do++,X)},y$T=function(v,q,x,X,y,Z,J,M,l){switch(J.tagName){case "b":M.bold=!0;
break;case "i":M.italic=!0;break;case "u":M.underline=!0}for(let a=0;a<J.childNodes.length;a++){var B=J.childNodes[a];if(B.nodeType===3)B=new hC(q,x,X,y.id,B.nodeValue,Z||a>0,g.Mf(M)?void 0:M),l.push(B),y.D.push(B);else{let S={};Object.assign(S,M);y$T(v,q,x,X,y,!0,B,S,l)}}},J$s=function(v,q,x){if(typeof q==="string"||KfB(q))return[{trackData:q,
oM:x}];if(typeof q==="string"&&q.substring(0,6)==="WEBVTT"||typeof q!=="string"&&X57(q))return[{trackData:q,oM:x}];var X=new DataView(q);if(X.byteLength<=8||X.getUint32(4)!==1718909296)return[];var y=g.Wk(X);if(v.rY&&y){var Z=g.xu(y),J=g.XD(y);y=y.segmentNumber;Z&&y&&v.rY.Yh(y,Z,J)}v=g.Cj(X,1835295092);if(!v||!v.length||!v[0].size)return[];Z=[];for(J=0;J<v.length;J++)y=v[J],y=new Uint8Array(q,y.dataOffset,y.size-(y.dataOffset-y.offset)),y=g.tL(y),Z.push({trackData:y,oM:x+J*1E3});Z$r(X,Z,x);return Z=
Z.filter(M=>!!M.trackData)},o6O=function(v,q,x){v.D||(v.D=new g6s);
v=v.D.O(q,x);Math.random()<.01&&g.WL(Error("Deprecated subtitles format in web player: WebVTT"));return v},Z$r=function(v,q,x){var X=g.gW(v,0,1836476516),y=9E4;
X&&(y=g.Mv(X)||9E4);X=0;var Z=g.Cj(v,1836019558);for(let M=0;M<Z.length;M++){var J=Z[M];M<q.length&&(J=g.gW(v,J.dataOffset,1953653094))&&(J=g.gW(v,J.dataOffset,1952867444))&&(J=g.Nv(J)/y*1E3,M===0&&(X=J),q[M].oM=J-X+x||x*M*1E3)}},jBr=function(v){var q={};
if(v=g.gL(v))q.lang=v,g.lD5.test(v)&&(q.Xg=1);return q},KT=function(v){return v.O==="HLS"&&v.nF?!0:v.BA&&v.nF&&v.O!=="LIVE"&&v.O!=="SABR_LIVE"},M7x=function(v){return!v.j&&v.BA&&v.cA&&(v.O==="LIVE"||v.O==="SABR_LIVE")},Or=function(v,q,x=!1){var X=v.B.N("enable_player_captions_new_style_defaults")?lnx:GiB,y=X.pW;
v.C={};Object.assign(v.C,X);v.C.pW={};Object.assign(v.C.pW,y);v.L={pW:{}};var Z=q.backgroundOverride?v.L:v.C,J=q.background||y.background;fT.test(J);Z.pW.background=J;Z=q.colorOverride?v.L:v.C;J=q.color||y.color;fT.test(J);Z.pW.color=J;Z=q.windowColorOverride?v.L:v.C;J=q.windowColor||X.windowColor;fT.test(J);Z.windowColor=J;Z=q.backgroundOpacityOverride?v.L:v.C;J=q.backgroundOpacity;J==null&&(J=y.backgroundOpacity);Z.pW.backgroundOpacity=J;Z=q.fontSizeIncrementOverride?v.L:v.C;J=q.fontSizeIncrement;
J==null&&(J=y.fontSizeIncrement);Z.pW.fontSizeIncrement=J;J=q.fontStyleOverride?v.L:v.C;Z=q.fontStyle;Z==null&&(Z=y.bold&&y.italic?3:y.bold?1:y.italic?2:0);J=J.pW;switch(Z){case 1:J.bold=!0;delete J.italic;break;case 2:delete J.bold;J.italic=!0;break;case 3:J.bold=!0;J.italic=!0;break;default:delete J.bold,delete J.italic}Z=q.textOpacityOverride?v.L:v.C;J=q.textOpacity;J==null&&(J=y.textOpacity);Z.pW.textOpacity=J;Z=q.windowOpacityOverride?v.L:v.C;J=q.windowOpacity;J==null&&(J=X.windowOpacity);Z.windowOpacity=
J;X=q.charEdgeStyleOverride?v.L:v.C;Z=q.charEdgeStyle;Z==null&&(Z=y.charEdgeStyle);X.pW.charEdgeStyle=Z;X=q.fontFamilyOverride?v.L:v.C;Z=q.fontFamily;Z==null&&(Z=y.fontFamily);X.pW.fontFamily=Z;v.loaded&&v.Ey();x&&g.Rq("yt-player-caption-display-settings",q,2592E3)},$F=function(v,q,x){q&&!v.V?(q=rHr({Xg:0,
lang:"ko"}),v.V=[q,new hC(q.start,q.end-q.start,0,q.id,x??"\uc790\ub9c9\uc740 \uc774\ub807\uac8c \ud45c\uc2dc\ub429\ub2c8\ub2e4.")],v.player.gN(v.V)):!q&&v.V&&(A$K(v,v.V),v.V=null)},BaK=function(v){if(v.B.N("enable_player_captions_persistence_state_machine")){var q=g.zQ("yt-player-caption-persistence");
if(q==null){let x=g.P0().yY(65);if(x===!0)q=!1;else{let X=g.b6(v.B)?PQ(v):Nag(v);X!=null?q=!!X:x===!1&&(q=!0)}q!==void 0&&T0(v,q)}return q}},PQ=function(v){if(!v.U.isInline())return g.zQ("yt-player-sticky-caption")},Nag=function(v){if(!v.storage)return null;
try{var q=v.storage.get("module-enabled")}catch(x){v.storage.remove("module-enabled")}return q},LT=function(v){if(v.B.N("enable_player_captions_persistence_state_machine"))return BaK(v);
var q=void 0,x=g.P0().yY(65);if(g.b6(v.B)&&x!=null){if(PQ(v)!=null)return!1;q=!x}return q},CJr=function(v){if(v.B.zy===1||v.videoData.U$===1||g.ny(v.videoData,"yt:cc")==="alwayson")return!0;
if(v.videoData.captionTracks.length)var q=v.getAudioTrack().X;if(v.B.N("enable_player_captions_persistence_state_machine")){var x=BaK(v);if(x!==void 0)return!!x}else if(v.B.zy===2&&(g.b6(v.B)?x=PQ(v):x=Nag(v),x!=null))return!!x;x=Si(v.player.getAudioTrack(),g.b6(v.B));var X=g.ny(v.videoData,"yt:cc");if(LT(v)===void 0){if(x==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return X?X==="on":!0;if(x==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return X==="on"}else return X==="on";return q==="ON"||g.ny(v.videoData,
"yt:cc")==="on"},Er=function(v,q=!1){if(v.X&&!q||!v.videoData.captionTracks.length)return!1;
v=v.getAudioTrack();return!!v.D||v.X==="FORCED_ON"},anK=function(v){return v.B.N("html5_honor_caption_availabilities_in_audio_track")&&v.O!=="LIVE"&&v.O!=="SABR_LIVE"},SF_=function(v,q){if(v.X){var x=v.U.j2().AB().textTracks,X=null;
v.O==="HLS"?X=v.X.getId():X=v.X.toString();for(let Z=0;Z<x.length;Z++){var y=x[Z];y.id===X&&(q?y.mode!=="showing"&&(y.mode="showing",y=v.X,v.r4(y,!!y,uw(v)?"g":v.Y?"m":"s")):y.mode==="showing"&&(y.mode="disabled"))}}},uw=function(v){var q=Fv(v);
return!!q&&v.X===q},WQ_=function(v,q){if(v.O==="HLS")return!1;
g.OW(v.videoData)&&(q=!0);q||(q=v.O==="TTS"?!1:v.O==="INNERTUBE"?!1:!0);return q||v.B.N("web_watch_disable_account_level_captions_settings")&&g.b6(v.B)?!0:!!g.P0().yY(66)},Fv=function(v){return v.G&&v.G.D},vc=function(v,q){if(!v.D)return null;
if(v.G&&v.G.j)return v.G.j;q=WQ_(v,q);q=v.D.D.D(q);var x=null;if(vGs(v.B)){var X=v.U.isInline()?void 0:g.zQ("yt-player-caption-sticky-language");var y=[X,v.videoData.captionsLanguagePreference,v.B.captionsLanguagePreference,g.ny(v.videoData,"yt:cc_default_lang")];let M=!1;for(let l=0;l<y.length;l++){let B=y[l];if(B){M=!0;for(var Z=0;Z<q.length;Z++)if(g.gL(q[Z])===B)return q[Z];for(Z=0;Z<q.length;Z++)if(g.gL(q[Z]).split("-")[0]===B.split("-")[0])return q[Z]}}if(M&&v.D&&(y=v.D.G,y.length))for(var J of y)if(J.languageCode===
X){x=J;break}}else for(J=[v.videoData.captionsLanguagePreference,v.B.captionsLanguagePreference,g.ny(v.videoData,"yt:cc_default_lang")],X=0;X<J.length;X++)for(y=0;y<q.length;y++)if(g.gL(q[y])===J[X])return q[y];J=null;v.G&&v.G.O&&(J=v.G.O);J||(J=q.find(M=>M.isDefault)||null);
J||(J=q[0]||Fv(v));J&&x&&g.gL(J).split("-")[0]!==x.languageCode.split("-")[0]&&(J=F1O(J,x));return J},Iny=function(v,q){var x=v.D.D.D(!0),X=[];
for(let y=0;y<x.length;y++){let Z=x[y],J=g.K1("TRACK");J.setAttribute("kind","subtitles");J.setAttribute("label",g.Jm(Z));J.setAttribute("srclang",g.gL(Z));J.setAttribute("id",Z.toString());v.wO||J.setAttribute("src",v.D.L(Z,"vtt"));Z===q&&J.setAttribute("default","1");X.push(J)}q=v.U.j2();q.F3(X);X=q.AB();v.cA&&v.F3.D3(X.textTracks,"change",v.mk)},XL=function(v,q,x){v.loaded&&v.unload();
x!=null&&(v.Y=x,v.Y&&(v.B.N("enable_player_captions_persistence_state_machine")?T0(v,!!q):g.b6(v.B)?sE(v,!!q):qt(v,!!q)));q!==null||Er(v,!0)||v.r4(q,!!q,v.Y?"m":"s");v.X=q;Er(v)&&(v.X=Fv(v));xL(v,v.X??void 0);v.load()},T0=function(v,q){v.B.N("enable_player_captions_persistence_state_machine")&&g.Rq("yt-player-caption-persistence",q,3122064E3)},sE=function(v,q){v.U.isInline()||g.Rq("yt-player-sticky-caption",q,2592E3)},qt=function(v,q){if(v.storage)try{v.storage.set("module-enabled",q)}catch(x){}},
xL=function(v,q){v.B.N("html5_modify_caption_vss_logging")&&(v.videoData.I5=q)},p5O=function(v,q){var x=v.Oy[q.id];
x&&x.O!==q&&(x.dispose(),delete v.Oy[q.id],x=null);x||(x=b$y(v,q))&&(v.Oy[q.id]=x)},YFs=function(v,q){var x=q.windowId;
v.vA[x]||(v.vA[x]=[]);v.vA[x].push(q)},b$y=function(v,q){var x=c$x(v);
if(!x)return null;var X=v.X?g.gL(v.X):null;X&&g.lD5.test(X)&&(q.params.Xg=1);var y=v.Ok.getPlayerSize();X=y.height*v.hk.height;y=y.width*v.hk.width;v.B.playerStyle!=="google-live"||v.C.isDefault||Object.assign(q.params,v.C);switch(q.params.zL!=null?q.params.zL:q.D.length>1?1:0){case 1:return new eST(q,v.C,v.L,x.width,x.height,y,X,v.B.experiments,v.Z3.bind(v),v.U);case 2:return new t76(q,v.C,v.L,x.width,x.height,y,X,v.B.experiments,v.Z3.bind(v),v.U);default:return new yX(q,v.C,v.L,x.width,x.height,
y,X,v.B.experiments,v.Z3.bind(v),v.U)}},c$x=function(v){var q=v.Ok.getVideoContentRect(!0).height,x=v.Ok.getVideoContentRect(!0).width;
if(!q||!x)return null;q*=v.hk.height;x*=v.hk.width;return{width:x,height:q}},A$K=function(v,q){v.player.zG(q);
for(let x of q)g.TJ(v.rO,x);CT(v.gO)},V76=function(v,q){if(!v.D)return{};
if(q){g.Mf(q)||v.pa(q.vss_id,"m");if(v.j&&v.O!=="HLS"||!g.Ws(q))return;if(g.Mf(q)){XL(v,null,!0);return}let X;var x=v.D.D.D(!0);for(let y=0;y<x.length;y++){let Z=x[y];Z.languageCode!==q.languageCode||X&&(Z.languageName!==q.languageName||(Z.captionId||"")!==(q.captionId||"")||g.Jm(Z)!==q.displayName)||(X=q.translationLanguage?F1O(Z,q.translationLanguage):Z)}v.NV(q.position);!X||X===v.X&&v.loaded||(q=g.h1(),x=g.gL(X),q.length&&x===q[q.length-1]||(q.push(x),g.Rq("yt-player-caption-language-preferences",
q)),vGs(v.B)&&!v.U.isInline()&&g.Rq("yt-player-caption-sticky-language",x,2592E3),XL(v,X,!0))}else return v.loaded&&v.X&&!uw(v)?av(v.X):{};return""};
g.e_.prototype.Yh=g.X7(134,function(v,q,x){this.X.set(v,{LG:q,U9:x})});
g.tU.prototype.Yh=g.X7(133,function(v,q,x){this.F3.Yh(v,q,x)});
g.li.prototype.G=g.X7(132,function(){this.mediaElement.G()});
g.gm.prototype.G=g.X7(131,function(){var v=g.cX(document,"track",void 0,this.D);for(let q=0;q<v.length;q++)g.TK(v[q])});
g.li.prototype.q4=g.X7(130,function(){return this.mediaElement.q4()});
g.gm.prototype.q4=g.X7(129,function(){return!(!this.D.textTracks||!this.D.textTracks.addEventListener)});
g.li.prototype.vA=g.X7(128,function(){return this.mediaElement.vA()});
g.gm.prototype.vA=g.X7(127,function(){return!!this.D.textTracks});
g.li.prototype.F3=g.X7(126,function(v){this.mediaElement.F3(v)});
g.gm.prototype.F3=g.X7(125,function(v){for(let q=0;q<v.length;q++)this.D.appendChild(v[q])});
g.vz.prototype.pa=g.X7(48,function(v,q){this.app.HA().pa(v,q)});
g.Hl.prototype.pa=g.X7(47,function(v,q){this.S.pa(v,q)});
g.Nz.prototype.pa=g.X7(46,function(v,q){v=[v,q];g.Qh(this,g.hh(this.provider),"cfi",v)});
g.a7.prototype.pa=g.X7(45,function(v,q){this.qoe&&this.qoe.pa(v,q)});
g.d7.prototype.pa=g.X7(44,function(v,q){this.B_.pa(v,q)});
g.pi.prototype.pa=g.X7(43,function(){});
g.z5.prototype.pa=g.X7(42,function(v,q){g.NR(this,37,[v,q])});
g.vz.prototype.r4=g.X7(41,function(v,q,x){this.app.HA().r4(v,q,x)});
g.Hl.prototype.r4=g.X7(40,function(v,q,x){this.S.r4(v,q,x)});
g.Nz.prototype.r4=g.X7(39,function(v,q,x){if(this.Jk!==v||this.qH!==q)q=q==="rawcc"?"":q,x=[v,q,this.Jk,x],g.Qh(this,g.hh(this.provider),"cfs",x),this.Jk=v,this.qH=q});
g.a7.prototype.r4=g.X7(38,function(v,q,x){this.qoe&&this.qoe.r4(v,q,x)});
g.d7.prototype.r4=g.X7(37,function(v,q,x){this.B_.r4(v,q,x)});
g.pi.prototype.r4=g.X7(36,function(){});
g.z5.prototype.r4=g.X7(35,function(v,q,x){g.NR(this,36,[v,q,x])});
g.E3.prototype.VB=g.X7(11,function(){return this.rY});
g.wj.prototype.VB=g.X7(10,function(){return this.HA().MS()});
g.vz.prototype.MS=g.X7(9,function(){return this.app.VB()});
g.Hl.prototype.MS=g.X7(8,function(){return this.S.MS()});
g.d7.prototype.MS=g.X7(7,function(){return this.loader?.VB()||null});
g.pi.prototype.MS=g.X7(6,function(){return null});
g.z5.prototype.MS=g.X7(5,function(){return null});
g.fQ.prototype.Ry=g.X7(3,function(v){return(v=this.O(v))?v.D:0});
g.RA.prototype.Ry=g.X7(2,function(){return 0});
var Xog=/#(.)(.)(.)/,xyy=/^#(?:[0-9a-f]{3}){1,2}$/i,QB2=class{constructor(){this.O=[];this.X=[]}D(v){return v?this.X.concat(this.O):this.X}},Z5=class extends g.Ok{constructor(v){super();this.Ak=v;this.D=new QB2;this.Oy=new QB2;this.C=null;this.G=[];this.hk=[]}K(){}j(){}O(){}L(){return""}F3(){return!1}NE(v,q){if(this.Ak.J().N("html5_dispatch_tracklist_loaded_event")){this.C&&(this.C.reject(),this.C=null);var x=[];this.Ak.X3("trackListLoaded",this.D,x,q);this.Ak.J().N("enable_po_decoration_of_forced_tracks")&&
this.Ak.X3("trackListLoaded",this.Oy,x,q);x.length?(q=new g.QM,q.promise.then(v.NE,()=>{}),this.C=q,Promise.all(x).then(q.resolve,q.reject).finally(()=>{this.C=null})):v.NE()}else v.NE()}QY(){this.C&&(this.C.reject(),this.C=null);
this.O();super.QY()}},w56={en:"English"},hS_=class extends Z5{constructor(v){super(v);this.X=new Set}j(v){var q=this.Ak.j2();if(q&&q.AB()){q=q.AB().textTracks;for(let x of q)x.kind==="subtitles"&&!this.X.has(x.language)&&x.language&&(bw(this.D,new g.yi({languageCode:x.language,languageName:x.language,kind:x.kind,id:x.id,displayName:w56[x.label]||x.label,vss_id:`.${x.language}`})),this.X.add(x.language))}this.D.D().length>0&&v.NE()}},DJO=class extends Z5{constructor(v,q,x){super(v);this.videoData=
q;this.audioTrack=x;this.X=null;this.Y=!1;this.G=q.xg;this.hk=q.Vj;this.Y=g.OW(q)}K(v,q,x){this.Ck();q=this.L(v,q);var X=this.Ak.J().N("html5_report_captions_ctmp_qoe"),y=(0,g.O)();this.O();ZHg(this,q,{format:"RAW",onSuccess:Z=>{this.X=null;if(X){var J=(Z.responseText.length/1024).toFixed();let M=(0,g.O)();this.videoData.W("capresp",{ms:M-y,kb:J})}J=Z.getResponseHeader&&Z.getResponseHeader("Content-Length")?Number(Z.getResponseHeader("Content-Length")):0;x.RO(Z.responseText,v,void 0,void 0,J)},
onError:X?Z=>{this.videoData.W("capfail",{status:Z?.status??0})}:void 0,
withCredentials:!0})}j(v){if(this.audioTrack){for(let q of this.audioTrack.captionTracks)bw(this.D,q);this.audioTrack.D&&bw(this.Oy,this.audioTrack.D)}this.NE(v,this.videoData.videoId)}L(v,q){var x=v.FQ(),X={fmt:q};if(q==="srv3"||q==="3"||q==="json3")g.TT()?Object.assign(X,{xorb:2,xobt:1,xovt:1}):Object.assign(X,{xorb:2,xobt:3,xovt:3});v.translationLanguage&&(X.tlang=g.gL(v));this.Y&&(X.xosf="1");Object.assign(X,this.Ak.J().D);return g.ER(x,X)}O(){this.X&&this.X.abort()}},UJK=class{constructor(){this.segments=
[]}contains(v){v=g.xY(this.segments,v);return v>=0||v<0&&(-v-1)%2===1}length(){return this.segments.length/2}},mJg=class extends g.Ok{constructor(v,q,x,X,y,Z){super();this.policy=v;this.player=q;this.Z=x;this.Y=X;this.C=y;this.wO=Z;this.j=new UJK;this.L=-1;this.X=this.O=this.D=null;this.hk=0;this.K=new g.YA(this.G,1E3,this);this.events=new g.zy(this);g.r(this,this.K);g.r(this,this.events);this.events.D3(q,"SEEK_COMPLETE",this.V);this.V();this.G()}QY(){super.QY();this.X&&this.X.cancel()}V(){this.seekTo(this.player.getCurrentTime())}seekTo(v){v-=
this.player.F4();var q=this.D;this.D=g.n2(this.Z.K(v).VY);q!==this.D&&this.wO&&this.wO()}reset(){this.j=new UJK;this.L=-1;this.X&&(this.X.cancel(),this.X=null)}G(){this.Ck();var v;if(v=this.D!=null)v=this.D,v=v.Z.j(v);if(v&&!this.X&&!(this.D&&this.D.segmentStartTime-this.player.getCurrentTime()>30)){v=this.D;v=v.Z.BA(v);let y=v.VY[0];if(this.player.getVideoData().enableServerStitchedDai){var q=this.player.MS();if(q){var x=y.Z.info.id;let Z=y.Kk;var X=v.VY[0].j;if(this.policy.gO){if(q=g.Ch_(q,X,Z,
x,3))v.j=q}else if(x=q.SF(X,Z,x,3))if(X=2,q.jY.has(Z)?X=0:g.nO(q,Z)&&(X=1),q=X,q===0)x&&(v.D=new g.DR(x));else if(q===2){this.K.start();gG2(this)&&this.seekTo(this.player.getCurrentTime());return}}}y.Z.index.BE(y.Kk)?(this.j.contains(v.VY[0].Kk)||oGO(this,v),this.D=g.n2(v.VY)):gG2(this)&&this.seekTo(this.player.getCurrentTime())}this.K.start()}},n67=class extends Z5{constructor(v,q){super(q);this.X=v;this.U=q;this.Y=null;this.V=!1;this.logger=new g.$k("caps");this.wO=g.h2(this.U,this.X)}K(v,q,x){this.O();
q=j32(this,v.getId());q||(q=v.languageCode,q=this.X.isManifestless?MSB(this,q,"386"):MSB(this,q));if(q){var X=(q.index.Ry(q.index.Yy())-q.index.getStartTime(q.index.Yy()))*1E3,y=new g.WMs(this.U.J());this.Y=new mJg(y,this.U,q,(Z,J)=>{x.RO(Z,v,J,X)},this.wO||g.qF(q.info),()=>{this.Y&&this.Y.reset();
this.V=!0})}}F3(){var v=this.V;
this.V=!1;return v}j(v){var q=this.U.J().N("html5_fallback_if_rawcc_missing");var x=this.X.D.rawcc!=null;if(!this.wO||!x&&q)q=this.X.isManifestless?lj7(this,"386"):lj7(this);else{if(!x){g.P7(this.logger,386248249,"rawcc used but unavailable");return}q=[new g.yi({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.yi({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}for(let X of q)bw(this.D,
X);v.NE()}O(){this.Y&&(this.Y.dispose(),this.Y=null)}L(){return""}},r$5=class extends Z5{constructor(v,q,x,X,y,Z){super(v);this.videoId=x;this.V=y;this.eventId=Z;this.wO={};this.X=null;v=X||g.Tm(q).hl||"";v=v.split("_").join("-");this.Y=g.ER(q,{hl:v})}K(v,q,x){this.Ck();q=this.L(v,q);this.O();this.X=g.Sw(q,{format:"RAW",onSuccess:X=>{this.X=null;var y=X.getResponseHeader&&X.getResponseHeader("Content-Length")?Number(X.getResponseHeader("Content-Length")):0;x.RO(X.responseText,v,void 0,void 0,y)},
withCredentials:!0})}j(v){var q=this.Y,x={type:"list",tlangs:1,v:this.videoId,vssids:1};this.V&&(x.asrs=1);q=g.ER(q,x);this.O();this.X=g.Sw(q,{format:"RAW",onSuccess:X=>{this.X=null;if((X=X.responseXML)&&X.firstChild){var y=X.getElementsByTagName("track");for(var Z=0;Z<y.length;Z++){var J=y[Z],M=J.getAttribute("lang_code");let l=J.getAttribute("lang_translated"),B=J.getAttribute("name"),a=J.getAttribute("kind"),S=J.getAttribute("id"),I=J.getAttribute("lang_default")==="true",b=J.getAttribute("cantran")===
"true";J=J.getAttribute("vss_id");bw(this.D,new g.yi({languageCode:M,languageName:l,name:B,kind:a,id:S,is_servable:!0,is_translateable:b,vss_id:J,is_default:I}))}X=X.getElementsByTagName("target");y=X.length;for(Z=0;Z<y;Z++)M={languageCode:X[Z].getAttribute("lang_code"),languageName:X[Z].getAttribute("lang_translated"),languageOriginal:X[Z].getAttribute("lang_original"),id:X[Z].getAttribute("id"),isDefault:X[Z].getAttribute("lang_default")==="true"},this.wO[M.languageCode]=M.languageName,this.G.push(M)}this.NE(v,
this.videoId)},
withCredentials:!0})}L(v,q){var x=this.Y;q={v:this.videoId,type:"track",lang:v.languageCode,name:v.getName(),kind:v.kind,fmt:q};var X=this.Ak.J();X.N("captions_url_add_ei")&&(q.ei=this.eventId);v.translationLanguage&&(q.tlang=g.gL(v));Object.assign(q,X.D);return x=g.ER(x,q)}O(){this.X&&this.X.abort()}},fT=/^#(?:[0-9a-f]{3}){1,2}$/i;var fnT=["left","right","center","justify"];var hC=class extends g.q_{constructor(v,q,x,X,y,Z=!1,J=null){super(v,v+q,{priority:x,namespace:"captions"});this.windowId=X;this.text=y;this.append=Z;this.D=J}toString(){return super.toString()}};var yX=class extends g.gu{constructor(v,q,x,X,y,Z,J,M,l,B){var a=B.isInline()&&!0,S={};Object.assign(S,q);Object.assign(S,v.params);Object.assign(S,x);var I={};Object.assign(I,q.pW);v.params.pW&&Object.assign(I,v.params.pW);Object.assign(I,x.pW);a&&(I.background&&(S.windowColor=I.background),S.windowOpacity=.6,I.backgroundOpacity=0);S.pW=I;var b=S.Xg===1,e=[{A:"span",dO:"captions-text",N4:{style:"word-wrap: normal; display: block;"}}],U=M.M4("caption_edit_on_hover")&&B.getVideoData().getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;
U&&e.unshift({A:"button",dO:"caption-edit",N4:{tabindex:"0","aria-label":iHr()},Im:[{A:"svg",N4:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},Im:[{A:"path",N4:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});super({A:"div",dO:"caption-window",N4:{id:`caption-window-${v.id}`,dir:b?"rtl":"ltr",tabindex:"0",lang:S.lang},Im:e});
this.experiments=M;this.G=[];this.BA=!1;this.O=v;this.vA=this.Rm=null;this.EL=Z;this.zm=J;this.K=null;this.maxWidth=Z*.96;this.maxHeight=J*.96;this.D=S;this.uI=x;this.F3=q;this.C=this.tk("captions-text");v=this.C.style;this.Jk=M.M4("enable_player_captions_new_style_defaults")&&("boxDecorationBreak"in v||"WebkitBoxDecorationBreak"in v);this.G4=Gpg(X,y,Z,J);this.q0=l;U&&(this.Y=this.tk("caption-edit"),this.D3(this.Y,"click",()=>{this.q0()}));
this.type=0;this.Z3=this.G4*AH6(I);this.cA=a;this.Ok=M.M4("enable_centered_caption_for_tvfilm_video")&&B.getVideoData().isTvfilmVideo;this.wO=B.J().fk().D.yY(g.Hly);this.Av=B.J().fk().D.yY(g.KI_);X=new g.Wz(this.element,!0);g.r(this,X);X.subscribe("dragstart",this.Ca,this);X.subscribe("dragmove",this.j0,this);X.subscribe("dragend",this.t2,this);this.Rb=this.yL=this.qH=this.Jv=0;X="";this.D.windowOpacity&&(X=WQ(this.D.windowColor),X="rgba("+X[0]+","+X[1]+","+X[2]+","+this.D.windowOpacity+")");y={"background-color":X,
display:this.D.isVisible===!1?"none":"","text-align":fnT[this.D.textAlign]};this.Jk&&(y["border-radius"]=X?`${this.Z3*.25}px`:"");(this.L=this.O.params.Xg===2||this.O.params.Xg===3)&&NcB(this,this.element);g.Ji(this.element,y);a&&this.element.parentElement?.style.setProperty("--caption-window-color",X);switch(this.D.NS){case 0:case 1:case 2:g.hy(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.hy(this.element,"ytp-caption-window-bottom")}}Ca(v,q){this.yL=v;this.Rb=q;var x=g.IX(this.element,
this.element.parentElement);this.Jv=v-x.x;this.qH=q-x.y}j0(v,q){if(v!==this.yL||q!==this.Rb){g.wF(this.element,"ytp-dragging")||g.hy(this.element,"ytp-dragging");var x=g.Yn(this.element);v=v-this.Jv-.02*this.EL;var X=q-this.qH-.02*this.zm,y=(v+x.width/2)/this.maxWidth*3;y=Math.floor(g.O5(y,0,2));var Z=(X+x.height/2)/this.maxHeight*3;Z=Math.floor(g.O5(Z,0,2));q=y+Z*3;v=(v+y/2*x.width)/this.maxWidth;v=g.O5(v,0,1)*100;x=(X+Z/2*x.height)/this.maxHeight;x=g.O5(x,0,1)*100;this.O.params.NS=q;this.O.params.V7=
x;this.O.params.K1=v;this.O.params.isDefault=!1;this.D.NS=q;this.D.V7=x;this.D.K1=v;this.D.isDefault=!1;this.F3.NS=q;this.F3.V7=x;this.F3.K1=v;this.F3.isDefault=!1;this.qF()}}t2(){g.U6(this.element,"ytp-dragging")}qF(){this.V(this.G)}V(v){var q=this.cA?0:Math.min(this.mk(),this.maxWidth),x=this.Xx(),X=this.cA;if(X){var y=getComputedStyle(this.C.parentNode);y=YF(y.borderLeftWidth)+YF(y.borderRightWidth)+YF(y.paddingLeft)+YF(y.paddingRight)}else y=0;var Z="";this.O.params.Xg===3&&(Z="rotate(180deg)");
var J=X?`calc(96% - ${y}px)`:"96%";g.Ji(this.element,{top:0,left:0,right:"",bottom:"",width:q?`${q}px`:"",height:x?`${x}px`:"","max-width":J,"max-height":J,margin:"",transform:""});this.Ey(v);Z={transform:Z,top:"",left:"",width:q?`${q}px`:"",height:x?`${x}px`:"","max-width":"","max-height":""};J=this.D.NS;var M=this.D.K1,l=this.D.V7;this.Ok&&J!=null&&(M=50,J=Math.floor(J/3)*3+1);M=M*.96+2;switch(J){case 0:case 3:case 6:(X=this.D.pW.fontSizeIncrement)&&X>0&&this.D.Xg!==2&&this.D.Xg!==3&&(M=Math.max(M/
(1+X*2),2));Z.left=`${M}%`;break;case 1:case 4:case 7:Z.left=`${M}%`;let B=0;this.wO||(B=this.C.offsetWidth);q||B?(q=q||B+1,Z.width=`${q}px`,Z["margin-left"]=X?`${q/-2-y/2}px`:`${q/-2}px`):(this.wO&&(Z.width="max-content"),Z.transform+=" translateX(-50%)");break;case 2:case 5:case 8:Z.right=`${100-M}%`}X=l*.96+2;switch(J){case 0:case 1:case 2:Z.top=`${X}%`;break;case 3:case 4:case 5:Z.top=`${X}%`;X=0;this.wO||(X=this.element.clientHeight);(x=x||X)?(Z.height=`${x}px`,Z["margin-top"]=`${x/-2}px`):Z.transform+=
" translateY(-50%)";break;case 6:case 7:case 8:Z.bottom=`${100-X}%`}if(this.Av){switch(J){case 0:case 3:case 6:x=Math.max(0,100-2*M);break;case 2:case 5:case 8:x=Math.max(0,100-2*(100-M));break;default:x=Math.max(0,2*Math.min(M-2,98-M))}Z["max-width"]=y>0?`calc(${x}% - ${y}px)`:`${x}%`}g.Ji(this.element,Z);this.Y&&(this.wO?x=this.Z3:(v=Csy(this,v),x=this.Ok?v>0?this.C.offsetHeight/v:0:this.C.offsetHeight/v),this.Y.style.height=`${x}px`,this.Y.style.width=`${x}px`,this.element.style.paddingLeft=`${x+
5}px`,this.element.style.paddingRight=`${x+5}px`,this.wO||(v=Number(this.element.style.marginLeft.replace("px",""))-x-5,x=Number(this.element.style.marginRight.replace("px",""))-x-5,this.element.style.marginLeft=`${v}px`,this.element.style.marginRight=`${x}px`))}Ey(v){if(this.type===0&&this.O.params.U0!==void 0&&this.experiments.M4("web_enable_popon_asr_captions")){var q=v,x=this.O.params.U0;if(q.length===0||x<=0)v=[];else{v=[];for(let y=q.length-1;y>=0;y--){var X=q[y];v.unshift(X);let Z=Csy(this,
v);if(Z>x){v.shift();typeof X.text==="string"&&(q=X.text.split("\n"),x=Z-x,q.length-x>0&&(x=q.slice(x),X=new hC(X.start,X.end-X.start,X.priority||0,X.windowId,x.join("\n"),X.append,X.D),v.unshift(X)));break}}}}for(X=0;X<v.length&&v[X]===this.G[X];X++);if(this.BA||this.G.length>X)X=0,this.BA=!1,this.G=[],this.K=this.vA=this.Rm=null,g.$U(this.C);for(;X<v.length;X++)Wf6(this,v[X])}mk(){return 0}Xx(){return 0}toString(){return super.toString()}};var RSy=class{constructor(){this.O=this.time=this.mode=this.X=0;this.j=new kiO(this);this.C=new kiO(this);this.D=[];this.clear()}clear(){this.O=this.time=this.mode=0;this.D=[];this.reset()}reset(){this.mode=0;this.j.reset(0);this.C.reset(1)}},Ijr=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,
74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,
215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255],zSO=class{constructor(){this.type=0}set(v){this.type=v}get(){return this.type}},dJs=class{constructor(){this.state=this.wb=this.TO=0}clear(){this.state=0}update(){this.state=this.state===2?1:0}cG(){return this.state!==0}matches(v,q){return this.cG()&&v===this.TO&&q===this.wb}},H$7=class{constructor(){this.timestamp=this.D=0}copy(v){this.D=v.D;
this.timestamp=v.timestamp}reset(){this.timestamp=this.D=0}},J_=class{constructor(v){this.C=v;this.O=[];this.D=this.X=this.row=0;this.style=new zSO;this.j=0;for(v=0;v<=15;v++){this.O[v]=[];for(let q=0;q<=32;q++)this.O[v][q]=new H$7}}updateTime(v){for(let q=1;q<=15;++q)for(let x=1;x<=32;++x)this.O[q][x].timestamp=v}debugString(){var v="\n";for(let q=1;q<=15;++q){for(let x=1;x<=32;++x){let X=this.O[q][x];v=X.D===0?v+"_":v+String.fromCharCode(X.D)}v+="\n"}return v}reset(v){for(let q=0;q<=15;q++)for(let x=
0;x<=32;x++)this.O[q][x].reset();this.j=v;this.D=0;this.X=this.row=1}},eAs=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],tSO=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],VS7=[193,201,211,218,220,252,8216,
161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,206,207,239,212,217,249,219,171,187],Q3_=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499],KQO=class{constructor(v){this.O=v;this.C=0;this.style=new zSO;this.L=new J_(this.O);this.K=new J_(this.O);this.text=new J_(this.O);this.X=this.L;this.j=this.K;this.D=this.X}reset(v,q){this.C=q;this.style.set(2);this.X=this.L;this.j=this.K;this.D=this.X;var x=(v<<
2)+(q<<1);this.L.reset(x);this.K.reset(x);this.text.reset((v<<2)+(q<<1)+1)}},kiO=class{constructor(v){this.D=v;this.C=0;this.O=new KQO(this.D);this.L=new KQO(this.D);this.X=new dJs;this.j=this.O}reset(v){this.C=v;this.X.clear();this.j=this.O;this.O.reset(v,0);this.L.reset(v,1)}};var O$K=class{j(){}};var gg=class extends g.Ok{reset(){}};var Ur=class extends g.q_{constructor(v,q,x,X,y){super(v,v+q,{priority:x,namespace:"captions"});this.id=X;this.params=y;this.D=[]}toString(){return super.toString()}},Do=0;var $Jr=class extends gg{constructor(v){super();this.j=v;this.pens={};this.Y={};this.G={};this.C="_"+Do++;this.K={};this.X=this.D=null;this.L=!0}reset(){this.K={};this.X=this.D=null;this.L=!0}O(v,q){v=v.firstChild;v.getAttribute("format");q=q||0;Number.isFinite(q);v=Array.from(v.childNodes);for(var x of v)if(x.nodeType===1)switch(x.tagName){case "head":var X=x;break;case "body":var y=x}if(X){X=Array.from(X.childNodes);for(var Z of X)if(Z.nodeType===1)switch(Z.tagName){case "pen":x=Z.getAttribute("id");
X=this.pens;v={};var J=Z.getAttribute("p");J&&Object.assign(v,this.pens[J]);J=nT(Z,"b");J!=null&&(v.bold=J);J=nT(Z,"i");J!=null&&(v.italic=J);J=nT(Z,"u");J!=null&&(v.underline=J);J=r0(Z,"et");J!=null&&(v.charEdgeStyle=J);J=r0(Z,"of");J!=null&&(v.offset=J);J=kF(Z,"bc");J!=null&&(v.background=J);J=kF(Z,"ec");J!=null&&(v.kL=J);J=kF(Z,"fc");J!=null&&(v.color=J);J=r0(Z,"fs");J!=null&&J!==0&&(v.fontFamily=J);J=mt(Z,"sz");J!==void 0&&(v.fontSizeIncrement=J/100-1);J=mt(Z,"bo");J!==void 0&&(v.backgroundOpacity=
J/255);J=mt(Z,"fo");J!==void 0&&(v.textOpacity=J/255);J=r0(Z,"rb");J!=null&&J!==10&&J!==0&&(v.kv=J>10?J-1:J);J=r0(Z,"hg");J!=null&&(v.SO=J);X[x]=v;break;case "ws":X=Z.getAttribute("id");this.G[X]=fj7(this,Z);break;case "wp":X=Z.getAttribute("id"),this.Y[X]=kpK(this,Z)}}if(y){Z=[];y=Array.from(y.childNodes);for(U of y)if(U.nodeType===1)switch(U.tagName){case "w":this.D=RA6(this,U,q,!1);(y=this.K[this.D.id])&&y.end>this.D.start&&(y.end=this.D.start);this.K[this.D.id]=this.D;Z.push(this.D);break;case "p":var M=
U;v=q;y=[];X=M.getAttribute("w")||this.C;x=!!nT(M,"a");v=(mt(M,"t")||0)+v;J=mt(M,"d")||5E3;x||(!this.L&&this.X&&this.X.windowId===X&&this.X.end>v&&(this.X.end=v),this.X&&this.X.text==="\n"&&(this.X.text=""));let R=x?6:5;var l=M.getAttribute("p");l=l?this.pens[l]:null;let f=Array.from(M.childNodes);f.length&&(this.L=M.getAttribute("d")!=null);for(M=0;M<f.length;M++){var B=f[M];var a=void 0;M>0&&(x=!0);let z;B.nodeType===1&&(z=B);if(z&&z.tagName==="s"){if((B=(B=z.getAttribute("p"))?this.pens[B]:null)&&
B.kv&&(B.kv===1?(B=f.slice(M,M+4),B.length===4&&(a=nG6(v,J,X,x,R,B,this.pens),M+=3)):a=nG6(v,J,X,x,R,[z],this.pens)),!a){var S=z;a=v;B=J;var I=X,b=x;let L=S.textContent?S.textContent:"";var e=S.getAttribute("p");e=e?this.pens[e]:null;S=mt(S,"t")||0;a=new hC(a+S,B-S,R,I,L,b,e)}}else a=new hC(v,J,R,X,B.textContent||"",x,l);y.push(a);this.X=a}if(y.length>0){y[0].windowId===this.C&&(this.D=RA6(this,U,q,!0),Z.push(this.D));for(let z of y)z.windowId=this.D.id,this.D.D.push(z),Z.push(z)}}var U=Z}else U=
[];return U}};var PJB=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]),Ta5=class extends gg{constructor(v){super();this.L=v;this.D=new Map;this.j=new Map;this.C=new Map;this.X=new Map}reset(){this.X.clear()}O(v,q){v=JSON.parse(v);if(!v)return[];if(v.pens){var x=v.pens,X=0;for(var y of x){x={};var Z=y.pParentId;Z&&Object.assign(x,this.D.get(Z));y.bAttr&&(x.bold=!0);y.iAttr&&(x.italic=!0);y.uAttr&&(x.underline=!0);Z=y.ofOffset;Z!=null&&(x.offset=Z);y.szPenSize!==void 0&&(x.fontSizeIncrement=y.szPenSize/100-1);
Z=y.etEdgeType;Z!=null&&(x.charEdgeStyle=Z);y.ecEdgeColor!==void 0&&(x.kL=Rv(y.ecEdgeColor));Z=y.fsFontStyle;Z!=null&&Z!==0&&(x.fontFamily=Z);y.fcForeColor!==void 0&&(x.color=Rv(y.fcForeColor));y.foForeAlpha!==void 0&&(x.textOpacity=y.foForeAlpha/255);y.bcBackColor!==void 0&&(x.background=Rv(y.bcBackColor));y.boBackAlpha!==void 0&&(x.backgroundOpacity=y.boBackAlpha/255);(Z=y.rbRuby)&&Z!==10&&(x.kv=Z>10?Z-1:Z,x.textEmphasis=PJB.get(x.kv));y.hgHorizGroup&&(x.SO=y.hgHorizGroup);this.D.set(X++,x)}}if(v.wsWinStyles){X=
v.wsWinStyles;y=0;for(var J of X)X={},(x=J.wsParentId)?Object.assign(X,this.C.get(x)):Object.assign(X,this.L),J.mhModeHint!==void 0&&(X.zL=J.mhModeHint),J.juJustifCode!==void 0&&(X.textAlign=J.juJustifCode),J.pdPrintDir!==void 0&&(X.Xg=J.pdPrintDir),J.sdScrollDir!==void 0&&(X.VE=J.sdScrollDir),J.wfcWinFillColor!==void 0&&(X.windowColor=Rv(J.wfcWinFillColor)),J.wfoWinFillAlpha!==void 0&&(X.windowOpacity=J.wfoWinFillAlpha/255),this.C.set(y++,X)}if(v.wpWinPositions){y=v.wpWinPositions;J=0;for(var M of y)y=
{},(X=M.wpParentId)&&Object.assign(y,this.j.get(X)),M.ahHorPos!==void 0&&(y.K1=M.ahHorPos),M.apPoint!==void 0&&(y.NS=M.apPoint),M.avVerPos!==void 0&&(y.V7=M.avVerPos),M.ccCols!==void 0&&(y.jC=M.ccCols),M.rcRows!==void 0&&(y.U0=M.rcRows),this.j.set(J++,y)}if(v.events){v=v.events;M=[];for(let sO of v)if(J=(sO.tStartMs||0)+q,y=sO.dDurationMs||0,sO.id)X=String(sO.id),v=zAO(this,sO,J,y,X),M.push(v),this.X.set(X,v);else{sO.wWinId?X=sO.wWinId.toString():(X="_"+Do++,v=zAO(this,sO,J,y,X),M.push(v),this.X.set(X,
v));var l;v=M;var B=sO;y===0&&(y=5E3);x=this.X.get(X);let oy=(Z=!!B.aAppend)?6:5,Ar=B.segs,px=null;B.pPenId&&(px=this.D.get(B.pPenId));for(B=0;B<Ar.length;B++){var a=Ar[B],S=a.utf8;if(S){var I=a.tOffsetMs||0;let VT=null;a.pPenId&&(VT=this.D.get(a.pPenId));if((x.params.zL!=null?x.params.zL:x.D.length>1?1:0)===2&&Z&&S==="\n")continue;a=null;var b=[];if(l=VT&&VT.kv===1)a:{l=Ar;var e=B;if(e+3>=l.length||!l[e+1].pPenId||!l[e+2].pPenId||!l[e+3].pPenId){l=!1;break a}var U=l[e+1].pPenId;(U=this.D.get(U))&&
U.kv&&U.kv===2?(U=l[e+2].pPenId,U=this.D.get(U),!U||!U.kv||U.kv<3?l=!1:(U=l[e+3].pPenId,l=(U=this.D.get(U))&&U.kv&&U.kv===2?!0:!1)):l=!1}if(l)I=Ar[B+1].utf8,a=Ar[B+3].utf8,l=Ar[B+2].utf8,e=this.D.get(Ar[B+2].pPenId),S=myB(S,I,l,a,e),a=new hC(J,y,oy,X,S,Z,VT),B+=3;else{if(S.indexOf("<")>-1){b=VT;l=px;e=J;U=y;var R=I,f=oy,z=Z;let $O=[];var L=pT(`<html>${S}</html>`);if(!L.getElementsByTagName("parsererror").length&&L.firstChild?.childNodes.length)for(let OO of L.firstChild.childNodes){L=OO.textContent?.replace(/\n/g,
"")??"";if(OO.nodeType===3&&(!L||L.match(/^ *$/)!=null))continue;let d6={};Object.assign(d6,b||l);switch(OO?.tagName){case "b":d6.bold=!0;break;case "i":d6.italic=!0;break;case "u":d6.underline=!0}$O.push(new hC(e+R,U-R,f,x.id,L,z,d6))}b=$O}b.length||(b=[new hC(J+I,y-I,oy,x.id,S,Z,VT||px)])}if(b.length)for(let $O of b)v.push($O),x.D.push($O);else a&&(v.push(a),x.D.push(a))}Z=!0}}q=M}else q=[];return q}};var LQO=class extends Z5{constructor(v,q,x){super(v);this.videoData=q;this.audioTrack=x;this.G=q.xg}K(v,q,x){q7g(this.videoData.videoId,v.vssId,x.RO)}j(v){if(this.audioTrack)for(let q of this.audioTrack.captionTracks)bw(this.D,q);v.NE()}};var eST=class extends yX{constructor(v,q,x,X,y,Z,J,M,l,B){super(v,q,x,X,y,Z,J,M,l,B);this.type=1}Ey(v){var q=this.O.D;super.Ey(v);for(v=v.length;v<q.length;v++){let y=q[v],Z;if(X&&y.D===x)Z=X;else{Z={};Object.assign(Z,y.D);Object.assign(Z,oax);var x=y.D;var X=Z}Wf6(this,y,Z)}}},oax={t0:!0};var dyK=class extends O$K{constructor(v,q){super();this.trackData=v;this.L=q;this.version=this.C=this.O=this.byteOffset=0;this.X=[];this.D=new DataView(this.trackData)}j(v,q,x,X,y){if(x<X){let Z="_"+Do++;x=x/1E3-this.L;X=X/1E3-this.L;v=new Ur(x,X-x,5,Z,{textAlign:0,NS:0,K1:q*2.5,V7:v*5.33});y=new hC(x,X-x,5,Z,y);this.X.push(v);this.X.push(y)}}},jGs=class extends gg{constructor(v,q){super();this.X=v;this.j=q;this.track=this.j.languageName==="CC3"?4:0;this.D=new RSy;this.D.X=1<<this.track}O(v){v=new dyK(v,
this.X);if(HHg(v)){for(;v.byteOffset<v.D.byteLength;)for(v.version===0?v.O=d0(v)*(1E3/45):v.version===1&&(v.O=d0(v)*4294967296+d0(v)),v.C=z0(v);v.C>0;v.C--){var q=z0(v);let x=z0(v),X=z0(v);q&4&&(q&3)===this.track&&(this.track===0||this.track===1)&&(q=this.D,q.D.push({time:v.O,type:this.track,QC:x,jv:X,order:q.D.length}))}cHT(this.D,v);return v.X}return[]}reset(){this.D.clear()}};var t76=class extends yX{constructor(v,q,x,X,y,Z,J,M,l,B){super(v,q,x,X,y,Z,J,M,l,B);this.type=2;this.rO=[];this.Oy=this.hk=this.q4=0;this.gO=NaN;this.Bi=0;this.vO=null;this.Pi=new g.YA(this.jb,433,this);this.Y&&(B.createClientVe(this.Y,this,167342),this.D3(this.Y,"click",()=>{B.logClick(this.Y)}),v=new g.Wz(this.element,!0),g.r(this,v),v.subscribe("hoverstart",()=>{B.logVisibility(this.Y,!0)},this));
g.hy(this.element,"ytp-caption-window-rollup");g.r(this,this.Pi);g.Ji(this.element,"overflow","hidden")}qF(){var v=this.Pi;v.stop();v.FO()}jb(){this.element.removeEventListener("transitionend",this.jb,!1);g.U6(this.element,"ytp-rollup-mode");this.V(this.vO,!0)}Xx(){return this.L?this.Oy:this.hk}mk(){return this.L?this.hk:this.Oy}V(v,q){this.vO=v;if(this.O.params.U0){var x=0;for(let X=0;X<this.G.length&&x<v.length;X++)this.G[X]===v[x]&&x++;x>0&&x<v.length&&(v=this.G.concat(v.slice(x)));this.Bi=this.Oy;
this.hk=this.Oy=0;super.V(v);PsB(this,q)}super.V(v)}};var MkB=class{constructor(v,q,x,X){this.U=v;this.C=q;this.logger=x;this.wY=X;this.fF=[];this.D=null;this.O=[];this.HF=[];this.X=null;v=this.U.J().experiments.D("html5_override_micro_discontinuities_threshold_ms");this.j=v>0?v:10}unload(){this.X!=null&&(this.U.removeEventListener("sabrCaptionsDataLoaded",this.X),this.X=null);this.fF=[];this.D=null;this.O=[];this.U.X3("sabrCaptionsBufferedRangesUpdated",this.fF)}K(v){return{formatId:g.XX(v.info.Z.info,this.wY),Kk:v.info.Kk+(this.wY?0:1),startTimeMs:v.info.j*
1E3,durationMs:v.info.K*1E3}}};var lJO=class extends Z5{constructor(v,q){super(q);this.X=v;this.U=q;this.logger=new g.$k("caps");this.Y=this.wO=null;this.V=new MkB(this.U,this,this.logger,this.X.wY)}K(v,q,x){this.O();q=v.getId();q=q!=null&&q in this.X.D?this.X.D[q]:null;q||(q=v.languageCode,q=this.X.isManifestless?sB5(this,q,"386"):sB5(this,q));q&&(this.Y=v,this.wO=q,Ffy(this.V,x),this.U.X3("sabrCaptionsTrackChanged",g.XX(q.info,this.X.wY)))}j(v){var q=this.X.isManifestless?qFK(this,"386"):qFK(this);for(let x of q)bw(this.D,x);
v.NE()}O(){this.Y&&(this.Y=this.wO=null,this.V.unload(),this.U.X3("sabrCaptionsTrackChanged",null))}L(){return""}};var xJg="WEBVTT".split("").map(v=>v.charCodeAt(0)),g6s=class extends gg{constructor(){super()}O(v,q){v instanceof ArrayBuffer&&(v=g.tL(new Uint8Array(v)));
var x=[];v=v.split(Gws);for(let e=1;e<v.length;e++){var X=v[e],y=q;if(X!==""&&!Ads.test(X)){var Z=o2.exec(X);if(Z&&Z.length>=4){var J=HQ(Z[1]),M=HQ(Z[2])-J;J+=y;var l=(Z=Z[3])?Z.split(" "):[];Z={};var B=null;var a="";var S=null,I="";for(let U of l){l=U.split(":");if(l.length!==2)continue;var b=l[1];switch(l[0]){case "line":l=b.split(",");l[0].endsWith("%")&&(B=l[0],Z.V7=Number.parseInt(B,10),l.length===2&&(a=l[1].trim()));break;case "position":l=b.split(",");S=l[0];Z.K1=Number.parseInt(S,10);l.length===
2&&(I=l[1].trim());break;case "align":switch(b){case "start":Z.textAlign=0;break;case "middle":Z.textAlign=2;break;case "end":Z.textAlign=1}}}B||a||(a="end");if(!S)switch(Z.textAlign){case 0:Z.K1=0;break;case 1:Z.K1=100;break;case 2:Z.K1=50}if(Z.textAlign!=null){B=0;switch(a){case "center":B+=3;break;case "end":B+=6;break;default:B+=0}switch(I){case "line-left":B+=0;break;case "center":B+=1;break;case "line-right":B+=2;break;default:switch(Z.textAlign){case 0:B+=0;break;case 2:B+=1;break;case 1:B+=
2}}a=B<0||B>8?7:B;Z.NS=a}X=X.substring(o2.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");I=Z;Z={};if(X.indexOf("<")<0&&X.indexOf("&")<0)y=i$6(J,M,5,I),J=new hC(J,M,5,y.id,X,!1,g.Mf(Z)?void 0:Z),x.push(y),x.push(J),y.D.push(J);else for(a=X.split(NB7),a.length===1?(X=5,I=i$6(J,M,X,I)):(B=X=6,I=Object.assign({jC:32},I),I=new Ur(J,M,B,"_"+Do++,I)),x.push(I),B=J,S=0;S<a.length;S++)if(l=a[S],S%2===0){b=pT(`<html>${l}</html>`);let U;b.getElementsByTagName("parsererror").length?(U=b.createElement("span"),
U.appendChild(b.createTextNode(l))):U=b.firstChild;y$T(this,B,M-(B-J),X,I,S>0,U,Z,x)}else B=HQ(l)+y}o2.lastIndex=0}}return x}},Ads=/^NOTE/,Gws=/(?:\r\n|\r|\n){2,}/,o2=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),NB7=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");var BBx=class extends g.Ok{constructor(v,q){super();this.U=v;this.B=q;this.D=null;this.rY=this.U.MS();this.logger=new g.$k("caps")}clear(){this.D&&this.D.dispose();this.D=null}reset(){this.D&&this.D.reset()}QY(){super.QY();this.clear()}};var GiB={windowColor:"#080808",windowOpacity:0,textAlign:2,NS:7,K1:50,V7:100,isDefault:!0,pW:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}},lnx={windowColor:"#080808",windowOpacity:0,textAlign:0,NS:7,K1:50,V7:100,isDefault:!0,pW:{background:"#080808",backgroundOpacity:.7,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.wR("captions",class extends g.bG{constructor(v){super(v);this.U=v;this.rO=[];this.Oy={};this.vA={};this.Y=!1;this.O="NONE";this.D=this.G=this.V=this.m3=this.G4=null;this.jb={NE:()=>{this.NE()},
RO:(X,y,Z,J,M=0)=>{var l=Number(this.videoData.J().fk().D.yY(g.FI_)??0);M>0&&l>0&&this.videoData.lengthSeconds>0&&M/this.videoData.lengthSeconds>l?this.U.W("tts",{dropcap:M}):this.RO(X,y,Z,J)}};
this.Jk=this.X=null;this.B=this.U.J();this.videoData=this.U.getVideoData();this.Ok=this.U.tv();this.C={pW:{}};this.L={pW:{}};g.Un(this.videoData)?this.O="OFFLINE":g.rXy(this.videoData,this.U)?this.O="HLS":v66(this.videoData,this.U)?this.O="SABR_LIVE":g.fm5(this.videoData,this.U)?this.O="LIVE":this.videoData.captionTracks.length?this.O="INNERTUBE":this.videoData.yL&&(this.O="TTS");this.BA=this.B.controlsType==="3";this.q4=new BBx(this.U,this.B);this.F3=new g.zy(this);this.K=new g.gu({A:"div",dO:"ytp-caption-window-container",
N4:{id:"ytp-caption-window-container"}});this.hk={top:0,right:0,bottom:0,left:0,width:1,height:1};var q=null,x=g.yB("yt-html5-player-modules::subtitlesModuleData");x&&(q=new g.Pr(x));this.storage=q;q=v.j2();this.nF=!!q?.vA();this.cA=!!q?.q4();this.j=KT(this);this.wO=M7x(this);g.r(this,this.q4);this.j?this.Rm=this.gO=null:(this.gO=new g.Ix(this.yL,void 0,this),g.r(this,this.gO),this.Rm=new g.YA(this.NF,2E3,this),g.r(this,this.Rm));g.r(this,this.F3);g.mq(this.player,this.K.element,4);g.r(this,this.K);
this.j||this.F3.D3(v,"resize",this.Ey);q=g.ZI(this.B)&&!g.c0()&&!this.U.isFullscreen();x=this.B.fk().D.yY(g.IEB)&&g.aH(this.B)&&g.XW;(this.Av=(q||x)&&!this.j&&!this.wO)&&this.F3.D3(v,q?"resize":"fullscreentoggled",this.Jv);this.F3.D3(v,"onPlaybackAudioChange",this.Rb);this.F3.D3(v,g.vh("captions"),X=>{this.onCueRangeEnter(X)});
this.F3.D3(v,g.sd("captions"),X=>{this.onCueRangeExit(X)});
Or(this,Iv()||{});g.as(this.player,"onCaptionsModuleAvailable");this.O==="HLS"&&this.j&&(v=this.U.j2().AB(),this.cA&&this.F3.D3(v.textTracks,"addtrack",this.qH))}QY(){if(this.j||this.wO){let v=this.U.j2();v&&!v.Ck()&&v.G()}else $F(this,!1);super.QY()}so(){if(this.BA)return this.j||this.wO;if(this.O==="HLS")return this.j;var v=this.getAudioTrack();if(anK(this)){if(!v.captionTracks.length)return!1;if(!this.D)return!0}v=Si(v,g.b6(this.B));return v==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:v==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?
Er(this):LT(this)||Er(this)?!0:CJr(this)}load(){super.load();this.G=this.getAudioTrack();if(this.D)this.X&&(this.q4.clear(),this.j?SF_(this,!0):this.player.getPresentingPlayerType()!==3&&this.D.K(this.X,"json3",this.jb),this.O!=="HLS"&&this.j||this.wO||uw(this)||g.as(this.player,"captionschanged",av(this.X)));else{if(this.O==="OFFLINE")var v=new LQO(this.player,this.videoData,this.getAudioTrack());else this.O==="SABR_LIVE"?v=new lJO(this.videoData.D,this.player):this.O==="HLS"?v=new hS_(this.player):
this.O==="LIVE"?v=new n67(this.videoData.D,this.player):this.O==="INNERTUBE"?v=new DJO(this.player,this.videoData,this.getAudioTrack()):(v=this.videoData,v=new r$5(this.player,this.videoData.yL,this.videoData.videoId,v.captionsLanguagePreference||v.z4.captionsLanguagePreference||g.ny(v,"yt:cc_default_lang")||v.z4.yL,this.videoData.Ti,this.videoData.eventId));this.D=v;g.r(this,this.D);this.D.j(this.jb)}}unload(){this.j&&this.X?SF_(this,!1):(this.Rm&&this.Rm.Nn(),this.player.KK("captions"),this.rO=
[],this.D&&this.D.O(),this.q4.clear(),this.V&&this.player.gN(this.V),this.Ey());super.unload();this.player.jp();g.as(this.player,"captionschanged",{})}create(){this.so()&&this.load();var v;a:{if(this.B.N("web_player_nitrate_promo_tooltip")&&this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.enableTouchCaptionsNitrate&&(v=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.captionTracks))for(let q of v)if(q.kind==="asr"&&q.languageCode==="en"){v=
!0;break a}v=!1}v&&this.U.X3("showpromotooltip",this.K.element)}NE(){var v=Si(this.player.getAudioTrack(),g.b6(this.B));v=v==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?vc(this,this.Y):v==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&Er(this)?Fv(this):LT(this)||this.Y||CJr(this)?vc(this,this.Y):Er(this)?Fv(this):null;this.O!=="HLS"&&this.j||this.wO?Iny(this,v):(!this.X&&v&&XL(this,v),g.as(this.player,"onCaptionsTrackListChanged"),g.S$(this.player,"onApiChange"))}mk(){var v=this.U.j2().AB().textTracks,q=null;
for(let x=0;x<v.length;x++)if(v[x].mode==="showing")a:{q=this.D.D.D(!0);for(let X=0;X<q.length;X++)if(q[X].toString()===v[x].id){q=q[X];break a}q=null}(this.loaded?this.X:null)!==q&&XL(this,q,!0)}qH(){this.D?.j(this.jb)}X8(){!this.X&&this.j||this.unload()}RO(v,q,x,X){if(v){xL(this,this.X??void 0);this.D.F3()&&(this.rO=[],this.U.KK("captions"),CT(this.gO),this.q4.reset());a:{var y=this.q4;X=X||0;x=J$s(y,v,x||0);v=[];try{for(let f of x){let z=f.trackData,L=f.oM,sO=y.B.N("safari_live_drm_captions_fix");
if(typeof z!=="string"){x=v;var Z=x.concat;if(sO&&X57(z))var J=o6O(y,z,L);else{var M=y,l=q,B=z,a=L,S=X;if(!KfB(B))throw Error("Invalid binary caption track data");M.D||(M.D=new jGs(S,l));J=M.D.O(B,a)}var I=Z.call(x,J)}else{if(z.substring(0,6)==="WEBVTT")var b=v.concat(o6O(y,z,L));else{x=v;var e=x.concat;b:{l=y;M=q;if(z[0]==="{")try{l.D||(l.D=new Ta5(jBr(M)));var U=l.D.O(z,L);break b}catch(px){g.af(px);U=[];break b}let oy=pT(z);if(!oy||!oy.firstChild){let px=Error("Invalid caption track data");px.params=
z;throw px;}if(oy.firstChild.tagName==="timedtext"){if(Number(oy.firstChild.getAttribute("format"))===3){B=oy;l.D||(l.D=new $Jr(jBr(M)));U=l.D.O(B,L);break b}let px=Error("Unsupported subtitles format in web player (Format2)");px.params=z;throw px;}if(oy.firstChild.tagName==="transcript"){let px=Error("Unsupported subtitles format in web player (Format1)");px.params=z;throw px;}let Ar=Error("Invalid caption track data");Ar.params=z;throw Ar;}b=e.call(x,U)}I=b}v=I}var R=v;break a}catch(f){g.P7(y.logger,
187101178,`Captions parsing failed: ${f.message}. `);y.clear();R=[];break a}R=void 0}this.B.N("html5_sabr_live_support_subfragmented_captions")&&this.D instanceof lJO&&(q=this.D.V,y=[],R.length>0&&(y=R.slice(q.O.length)),q.O=!q.D||q.D.info.VK?[]:R,R=y);R.length>0&&(q=this.X,this.r4(q,!!q,uw(this)?"g":this.Y?"m":"s"));this.player.gN(R,void 0,this.O==="LIVE"||this.O==="SABR_LIVE");!this.Y||this.wO||uw(this)||g.Cv(this.B)||g.AZ(this.B)||g.JZ(this.B)||this.B.Y==="shortspage"||this.player.isInline()||
(this.Rm.Nn(),R=rHr({NS:0,K1:5,V7:5,U0:2,textAlign:0,Xg:0,lang:"ko"}),this.m3=[R],q=["\uc124\uc815\uc744 \ud655\uc778\ud558\ub824\uba74 ","\uc744 \ud074\ub9ad\ud558\uc138\uc694."],this.G4||(y=new g.sS({A:"svg",N4:{height:"100%",version:"1.1",viewBox:"0 0 36 36",width:"100%"},Im:[{A:"path",Uo:!0,N4:{d:"m 23.94,18.78 c .03,-0.25 .05,-0.51 .05,-0.78 0,-0.27 -0.02,-0.52 -0.05,-0.78 l 1.68,-1.32 c .15,-0.12 .19,-0.33 .09,-0.51 l -1.6,-2.76 c -0.09,-0.17 -0.31,-0.24 -0.48,-0.17 l -1.99,.8 c -0.41,-0.32 -0.86,-0.58 -1.35,-0.78 l -0.30,-2.12 c -0.02,-0.19 -0.19,-0.33 -0.39,-0.33 l -3.2,0 c -0.2,0 -0.36,.14 -0.39,.33 l -0.30,2.12 c -0.48,.2 -0.93,.47 -1.35,.78 l -1.99,-0.8 c -0.18,-0.07 -0.39,0 -0.48,.17 l -1.6,2.76 c -0.10,.17 -0.05,.39 .09,.51 l 1.68,1.32 c -0.03,.25 -0.05,.52 -0.05,.78 0,.26 .02,.52 .05,.78 l -1.68,1.32 c -0.15,.12 -0.19,.33 -0.09,.51 l 1.6,2.76 c .09,.17 .31,.24 .48,.17 l 1.99,-0.8 c .41,.32 .86,.58 1.35,.78 l .30,2.12 c .02,.19 .19,.33 .39,.33 l 3.2,0 c .2,0 .36,-0.14 .39,-0.33 l .30,-2.12 c .48,-0.2 .93,-0.47 1.35,-0.78 l 1.99,.8 c .18,.07 .39,0 .48,-0.17 l 1.6,-2.76 c .09,-0.17 .05,-0.39 -0.09,-0.51 l -1.68,-1.32 0,0 z m -5.94,2.01 c -1.54,0 -2.8,-1.25 -2.8,-2.8 0,-1.54 1.25,-2.8 2.8,-2.8 1.54,0 2.8,1.25 2.8,2.8 0,1.54 -1.25,2.8 -2.8,2.8 l 0,0 z",
fill:"#fff"}}]}),g.r(this,y),this.G4=y.element),y=R.end-R.start,(I=g.Jm(this.X))&&this.m3.push(new hC(R.start,y,0,R.id,I)),this.m3.push(new hC(R.start,y,0,R.id,q[0]),new hC(R.start,y,0,R.id,this.G4,!0),new hC(R.start,y,0,R.id,q[1],!0)),this.player.gN(this.m3),g.cr(this.Rm));!this.Y||this.wO||uw(this)||(this.B.N("enable_player_captions_persistence_state_machine")?T0(this,!0):g.b6(this.B)?sE(this,!0):qt(this,!0),this.G&&(this.G.j=this.X),this.player.jp());this.Y=!1}}onCueRangeEnter(v){this.rO.push(v);
CT(this.gO)}onCueRangeExit(v){g.TJ(this.rO,v);this.D instanceof n67&&this.D.wO&&this.player.zG([v]);CT(this.gO)}getCaptionWindowContainerId(){return this.K.element.id}NF(){A$K(this,this.m3);this.m3=null}yL(){if(!this.Av||!this.j){this.gO.stop();g.lk(this.vA);this.rO.sort(g.FC);var v=this.rO;if(this.V){let q=g.f2(v,function(x){return this.V.indexOf(x)===-1},this);
q.length&&(v=q)}for(let q of v)q instanceof Ur?p5O(this,q):YFs(this,q);for(let [q,x]of Object.entries(this.Oy)){let X=q,y=x;this.vA[X]?(y.element.parentNode||(y instanceof t76||y instanceof eST||g.sz(this.Oy,(Z,J)=>{J!==X&&Z.O.params.NS===y.O.params.NS&&Z.O.params.K1===y.O.params.K1&&Z.O.params.V7===y.O.params.V7&&(Z.dispose(),delete this.Oy[J]);return J===X},this),this.K.element.appendChild(y.element)),y.V(this.vA[X])):(y.dispose(),delete this.Oy[X])}}}ON(){Or(this,{},!0);
g.as(this.player,"captionssettingschanged")}yf(){var v=this.B.N("enable_player_captions_new_style_defaults")?lnx:GiB,q=v.pW;v={background:q.background,backgroundOpacity:q.backgroundOpacity,charEdgeStyle:q.charEdgeStyle,color:q.color,fontFamily:q.fontFamily,fontSizeIncrement:q.fontSizeIncrement,fontStyle:q.bold&&q.italic?3:q.bold?1:q.italic?2:0,textOpacity:q.textOpacity,windowColor:v.windowColor,windowOpacity:v.windowOpacity};q=Iv()||{};q.background!=null&&(v.background=q.background);q.backgroundOverride!=
null&&(v.backgroundOverride=q.backgroundOverride);q.backgroundOpacity!=null&&(v.backgroundOpacity=q.backgroundOpacity);q.backgroundOpacityOverride!=null&&(v.backgroundOpacityOverride=q.backgroundOpacityOverride);q.charEdgeStyle!=null&&(v.charEdgeStyle=q.charEdgeStyle);q.charEdgeStyleOverride!=null&&(v.charEdgeStyleOverride=q.charEdgeStyleOverride);q.color!=null&&(v.color=q.color);q.colorOverride!=null&&(v.colorOverride=q.colorOverride);q.fontFamily!=null&&(v.fontFamily=q.fontFamily);q.fontFamilyOverride!=
null&&(v.fontFamilyOverride=q.fontFamilyOverride);q.fontSizeIncrement!=null&&(v.fontSizeIncrement=q.fontSizeIncrement);q.fontSizeIncrementOverride!=null&&(v.fontSizeIncrementOverride=q.fontSizeIncrementOverride);q.fontStyle!=null&&(v.fontStyle=q.fontStyle);q.fontStyleOverride!=null&&(v.fontStyleOverride=q.fontStyleOverride);q.textOpacity!=null&&(v.textOpacity=q.textOpacity);q.textOpacityOverride!=null&&(v.textOpacityOverride=q.textOpacityOverride);q.windowColor!=null&&(v.windowColor=q.windowColor);
q.windowColorOverride!=null&&(v.windowColorOverride=q.windowColorOverride);q.windowOpacity!=null&&(v.windowOpacity=q.windowOpacity);q.windowOpacityOverride!=null&&(v.windowOpacityOverride=q.windowOpacityOverride);return v}vT(v,q){var x={};Object.assign(x,Iv());Object.assign(x,v);Or(this,x,q);g.as(this.player,"captionssettingschanged")}Ey(){!this.j&&this.loaded&&(g.uC(this.Oy,function(v,q){v.dispose();delete this.Oy[q]},this),this.yL())}t4(v,q){switch(v){case "fontSize":if(isNaN(q))break;
v=g.O5(q,-2,4);this.vT({fontSizeIncrement:v});return v;case "reload":q&&!this.j&&XL(this,this.X,!0);break;case "stickyLoading":q!==void 0&&this.B.K&&(this.B.N("enable_player_captions_persistence_state_machine")?T0(this,!(!q||!q.userInitiated)):g.b6(this.B)?sE(this,!!q):qt(this,!!q));break;case "track":return V76(this,q);case "tracklist":return this.D?g.hr(this.D.D.D(!(!q||!q.includeAsr)),x=>av(x)):[];
case "translationLanguages":return this.D?this.D.G.map(x=>Object.assign({},x)):[];
case "sampleSubtitles":this.j||q===void 0||$F(this,!!q);break;case "sampleSubtitlesCustomized":this.j||$F(this,!!q,q);break;case "recommendedTranslationLanguages":return g.h1();case "defaultTranslationSourceTrackIndices":return this.D?this.D.hk:[]}}getOptions(){var v="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.B.K&&v.push("stickyLoading");return v}Vm(){var v=this.X;if(this.U.l5("captions")){if(this.B.N("html5_modify_caption_vss_logging"))return(v=this.videoData.I5??
null)?{cc:g.o$(v)}:{};if(v){let q=v.vssId;v.translationLanguage&&q&&(q=`t${q}.${g.gL(v)}`);return{cc:q}}}return{}}P5(v){this.isSubtitlesOn()?(this.B.N("enable_player_captions_persistence_state_machine")&&v?T0(this,!1):g.b6(this.B)?sE(this,!1):qt(this,!1),xL(this),XL(this,null,!0)):this.Kn(v)}Kn(v){var q=uw(this)||!this.X?vc(this,!0):this.X;q&&this.pa(q.vssId,"m");this.isSubtitlesOn()||XL(this,q,this.B.N("enable_player_captions_persistence_state_machine")?v:!0)}isSubtitlesOn(){return!!this.loaded&&
!!this.X&&!uw(this)}Rb(){var v=uw(this);Er(this,v)?XL(this,this.getAudioTrack().D,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),anK(this)&&(this.Y=!1,this.X=null,this.D&&(this.D.dispose(),this.D=null)),this.so()&&(v?XL(this,vc(this,!1),!1):this.load()))}bl(v){if(this.B.experiments.M4("web_enable_captions_set_target_container")&&v!==this.Jk){var q=this.K.element;q.parentNode&&g.TK(q);(this.Jk=v)?(this.Jk.appendChild(q),q.style.position="absolute",q.style.bottom="0",q.style.left=
"0",q.style.width="100%",q.style.height="auto",q.style.top="auto"):(g.mq(this.player,q,4),q.style.position="absolute",q.style.bottom="auto",q.style.left="0",q.style.width="100%",q.style.height="100%",q.style.top="0");this.Ey()}}NV(v){v&&(this.hk={top:v.top,right:v.right,bottom:v.bottom,left:v.left,width:1-v.left-v.right,height:1-v.top-v.bottom},this.K.element.style.top=`${this.hk.top*100}%`,this.K.element.style.left=`${this.hk.left*100}%`,this.K.element.style.width=`${this.hk.width*100}%`,this.K.element.style.height=
`${this.hk.height*100}%`,this.K.element.style.position="absolute",v=c$x(this))&&(this.K.element.style.width=`${v.width}px`,this.K.element.style.height=`${v.height}px`)}onVideoDataChange(v,q){v==="newdata"&&(this.videoData=q,this.loaded&&this.unload(),this.Y=!1,this.X=null,this.D&&(this.D.dispose(),this.D=null,g.as(this.player,"captionschanged",{})),this.so()&&this.load())}getAudioTrack(){return this.player.getAudioTrack()}Jv(){if(this.B.fk().D.yY(g.IEB)){this.loaded&&this.unload();var v=this.U.j2();
v&&!v.Ck()&&v.G();this.BA=this.U.isFullscreen()||this.B.controlsType==="3";this.j=KT(this);this.wO=M7x(this);this.D&&(this.j||this.wO)&&Iny(this,null)}else(v=this.U.j2())&&!v.Ck()&&v.G(),this.U.isFullscreen()?(this.j=this.BA=!0,this.loaded&&this.NE()):(this.BA=this.B.controlsType==="3",this.j=KT(this));XL(this,this.X)}Z3(){var v=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;v&&g.CU(this.player,"innertubeCommand",v)}r4(v,q,x){var X=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,
y="";v&&(y=v.vssId,y=y.replace(X,""));var Z="";v&&v.getId()&&(Z=v.getId()||"");v&&v.getXtags()&&(v=v.getXtags(),v=v.replace(X,""),Z=Z.concat(`;${v}`));this.O==="HLS"&&(Z="");this.U.r4(q?y:"",q?Z:"",x)}pa(v,q){v=(v||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");v.length>0&&this.U.pa(v,q)}});})(_yt_player);
