(function(g){var window=this;'use strict';var jt=function(v,q){if(!Number.isFinite(v))return String(v);v=String(v);var x=v.indexOf(".");x===-1&&(x=v.length);var X=v[0]==="-"?"-":"";X&&(v=v.substring(1));q="0".repeat(Math.max(0,q-x));return X+q+v},ln=function(v){typeof v==="number"?(this.date=Ces(v,0,1),Mt(this,1)):g.Ws(v)?(this.date=Ces(v.getFullYear(),v.getMonth(),v.getDate()),Mt(this,v.getDate())):(this.date=new Date(g.QT()),v=this.date.getDate(),this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),
Mt(this,v))},Ces=function(v,q,x){q=new Date(v,q,x);
v>=0&&v<100&&q.setFullYear(q.getFullYear()-1900);return q},Mt=function(v,q){v.getDate()!=q&&v.date.setUTCHours(v.date.getUTCHours()+(v.getDate()<q?1:-1))},GG=function(v){if(v.toggleButtonRenderer){var q=v.toggleButtonRenderer;
if(q.isToggled){var x=q.toggledText?g.of(q.toggledText):"";v.update({text:x,icon:aJO(q.toggledIcon)})}else x=q.defaultText?g.of(q.defaultText):"",v.update({text:x,icon:aJO(q.defaultIcon)});v.show()}else v.hide()},So6=function(v,q){!v.toggleButtonRenderer&&q&&q.toggleButtonRenderer?v.toggleButtonRenderer=q.toggleButtonRenderer:q&&q.toggleButtonRenderer||(v.toggleButtonRenderer=null);
GG(v)},aJO=function(v){if(!v)return null;
switch(v.iconType){case "NOTIFICATIONS":return{A:"svg",N4:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},Im:[{A:"path",N4:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]};case "NOTIFICATIONS_NONE":return{A:"svg",N4:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},Im:[{A:"path",N4:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]};
case "NOTIFICATIONS_ACTIVE":return{A:"svg",N4:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},Im:[{A:"path",N4:{d:"M7.58 4.08L6.15 2.65C3.75 4.48 2.17 7.3 2.03 10.5h2c.15-2.65 1.51-4.97 3.55-6.42zm12.39 6.42h2c-.15-3.2-1.73-6.02-4.12-7.85l-1.42 1.43c2.02 1.45 3.39 3.77 3.54 6.42zM18 11c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2v-5zm-6 11c.14 0 .27-.01.4-.04.65-.14 1.18-.58 1.44-1.18.1-.24.15-.5.15-.78h-4c.01 1.1.9 2 2.01 2z"}}]};
default:return null}},pYs=function(v,q){var x=g.k(q,Wus),X=g.k(q,IJs);
if(q&&(x||X)){if(x){var y=x;var Z="notification/add_upcoming_event_reminder"}else X&&(y=X,Z="notification/remove_upcoming_event_reminder");Z&&y&&y.params&&b05(v,Z,y.params)}},b05=function(v,q,x){var X=v.U.J();
v.D||(v.D=new g.$M(X.ks));var y={context:g.dT(v.D.config_||g.mT())};g.xs()&&(y.context.clientScreenNonce=g.xs());y.params=x;x={timeout:5E3,onError:()=>{Yoy(v)},
onTimeout:()=>{Yoy(v)}};
X.fk().D.yY(g.xGT)&&(x.onSuccess=Z=>{if(Z=Z.actions)for(let J of Z)g.CU(v.U,"innertubeCommand",J)});
g.Uf(v.D,q,y,x)},Yoy=function(v){v.toggleButtonRenderer&&(v.toggleButtonRenderer.isToggled=!v.toggleButtonRenderer.isToggled,GG(v))},A_=function(v,q,x){if(q){var X=q.subtitleText!=null?g.of(q.subtitleText):"";
x=x?x:q.mainText!=null?g.of(q.mainText):"";v.update({mainText:x,subtitleText:X,label:q.mainText?.accessibility?.accessibilityData?.label??x});g.m0(v.element,"ytp-offline-slate-single-text-line",!X);g.m0(v.C,"ytp-offline-slate-bar-hidden",!x&&!X)}},cd5=function(v){try{let q=JSON.parse(v);
return q!=null?q:void 0}catch(q){}},wYs=async function(v){var q=v.player.J(),x=v.getVideoData();
Nt(v)&&(eYK(v)?tk_(v,q,x):(VkO(v),await QGs(v,q,x)))},VkO=function(v){var q=v.getVideoData();
if(q.Wy)if(q.N("use_rta_for_player"))v.attestationResponse=hYs(v);else{let Z=new g.ZgB(q);if(g.$V.isInitialized()||v.sequenceNumber>=3){q=Promise;var x=q.resolve;let J=null;if(Z.videoData.XN){var X=g.LI(Z);if(X){J={};let M={};X=X.split("&");for(y of X)X=y.split("="),X.length===2&&(M[X[0]]=X[1]);var y=M;y.r1a&&(J.webResponse=y.r1a);y.r1c&&(J.error=Deg[Number(y.r1c)]);J.challenge=Z.videoData.XN}}v.attestationResponse=x.call(q,J||void 0)}}},naT=function(v){var q=v.getVideoData(),x=v.player.J();
if(q.isLivePlayback)if(g.cy(x.X)){v.j=!0;v.K=!0;if(!g.Cv(x)||g.cT(x))v.offlineSlate=new UeT(v.player),g.r(v,v.offlineSlate),g.mq(v.player,v.offlineSlate.element,4);(x=q.getPlayerResponse())&&x.playabilityStatus&&(v.D=x.playabilityStatus);v.D?.status!=="UNPLAYABLE"&&(v.D?(q=mes(void 0,v.D.liveStreamability&&v.D.liveStreamability.liveStreamabilityRenderer))?Bc(v,q):Bc(v,7500):q.N("html5_use_server_init_heartbeat_delay")?(q=CG(v),isNaN(q)||Bc(v,q)):Bc(v,1E3))}else v.player.KW("html5.unsupportedlive",
2,"HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1");else g.Oa(q.Yb,"heartbeat")&&v.player.dN("heartbeat",v.getPlayerType())},kwO=function(v,q,x){var X=x.liveStreamability&&x.liveStreamability.liveStreamabilityRenderer,y=!(!X||!(X.switchStreamsImmediately||X.transitionTiming&&X.transitionTiming==="STREAM_TRANSITION_TIMING_IMMEDIATELY"));
q=mes(q,X);var Z=v.getVideoData(),J=v.player.getPlayerStateObject(v.getPlayerType()),M=J.isPlaying()&&!g.fy(Z)&&!v.player.isAtLiveHead(v.getPlayerType());if(Z.J().zk()){var l=v.player.j2()?.DN()||{};l.status=x.status||"";l.dvr=`${+M}`;l["switch"]=`${+y}`;l.ended=`${+!(!X||!X.displayEndscreen)}`;v.player.W("heartbeat",l)}l=X&&X.broadcastId;var B=v.D&&v.D.liveStreamability&&v.D.liveStreamability.liveStreamabilityRenderer&&v.D.liveStreamability.liveStreamabilityRenderer.broadcastId,a=l!==B&&l!=null;
a&&v.player.W("lbidh",{broadcastId:l},!0);if(g.Cv(Z.J())&&X&&X.streamTransitionEndpoint){var S=g.k(X.streamTransitionEndpoint,g.Gy)?.commands||[];for(var I of S)if(g.k(I,g.Mk)?.signal==="RELOAD_PLAYER"){v.player.KW("qoe.restart",0,void 0,"sa.reload","7");break}}I=v.player.N("always_cache_redirect_endpoint");if(M&&!y&&!I)return q;S=X&&X.streamTransitionEndpoint&&g.k(X.streamTransitionEndpoint,g.zU);if((X&&X.transitionTiming)==="STREAM_TRANSITION_TIMING_AT_STREAM_END")v.getVideoData().transitionEndpointAtEndOfStream=
S;else{if(S&&rd2(v,S,x))return q;I&&!S&&v.getVideoData().transitionEndpointAtEndOfStream&&(v.getVideoData().transitionEndpointAtEndOfStream=void 0)}if(M&&!y&&I)return q;if(x.status.toUpperCase()==="OK"){if(!g.rs(Z)||a)return X={video_id:Z.videoId},Z.hm&&(X.is_live_destination="1"),X.disable_watch_next=!0,X.raw_watch_next_response=Z.getWatchNextResponse(),X.autonav_state=Z.autonavState,X.oauth_token=Z.oauthToken,X.vF=Z.vF,Z.A2&&(X.vss_credentials_token=Z.A2,X.vss_credentials_token_type=Z.eY),Z.Y&&
(X.vvt=Z.Y),y=void 0,g.rs(Z)?a&&(y=new fJs("broadcastIdChanged",`${B},${l}`),a2("HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",x)):(l&&(y=new fJs("formatsReceived",`${l}`)),a2("HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",x)),a&&v.player.W("lbidr",{broadcastId:l}),v.player.loadVideoByPlayerVars(X,void 0,void 0,void 0,y),q;v.player.dN("heartbeat",v.getPlayerType())}X&&X.displayEndscreen&&(v.offlineSlate?(v=v.offlineSlate,v.Y=!0,v.X&&v.api.OA()):J.isBuffering()&&(Z=v.player.j2()?.DN()||
{},v.player.W("hbse",Z,!0),v.player.OA(!0,"h"),g.CU(v.player,"onLiveMediaEnded",x)));return q},RYO=function(v){var q=v.getVideoData();
!q.N("use_rta_for_player")&&q.Wy&&(q=q.botguardData)&&g.Ta(q,v.player.J())},St=function(v){v.Y=0;
v.X.stop();v.C=!1;v.sequenceNumber=0},hYs=async function(v){if(await g.Vd())return v=v.getVideoData(),g.t6("ENGAGEMENT_TYPE_PLAYBACK",{cpn:v.clientPlaybackNonce,
encryptedVideoId:v.videoId||""},1500);if(v.sequenceNumber>=3)return{error:"ATTESTATION_ERROR_VM_INTERNAL_ERROR"}},CG=function(v){var q=v.getVideoData();
return q.N("html5_use_server_init_heartbeat_delay")?v.heartbeatParams?.interval?v.heartbeatParams.interval*1E3:q.uL:2E3},Bc=function(v,q){if(!v.X.isActive()&&v.K){var x=v.getVideoData();
if(Wc(v)||x.isLivePlayback)q===void 0&&(q=v.C?v.j?7500:v.heartbeatParams?.interval?v.heartbeatParams.interval*1E3:v.getVideoData().uL||6E4:1E3),v.X.start(q)}},eYK=function(v){var q=v.getVideoData();
if(!g.wx(v.getVideoData())||q.Mx)return!1;if(q.C){v=q.C.flavor==="playready";let x=q.C.flavor==="widevine"&&q.N("html5_innertube_heartbeats_for_widevine");q=g.lY(q.C)&&q.N("html5_innertube_heartbeats_for_fairplay");return!(v||x||q)}return!0},Wc=function(v){if(eYK(v))return!!v.heartbeatParams;
var q=v.getVideoData();return!g.wx(v.getVideoData())||q.KG||q.YE?!!q.heartbeatToken:!1},H0r=function(v,q,x){q.d_&&(x=g.md(x,{internalipoverride:q.d_}));
var X={cpn:q.clientPlaybackNonce};q.contextParams&&(X.context_params=q.contextParams);q.Rm&&(X.kpt=q.Rm);x=g.md(x,X);g.Sw(x,{format:"RAW",method:"GET",timeout:3E4,onSuccess:y=>{if(!v.X.isActive()&&Nt(v)){v.L.reset();v.sequenceNumber++;y=y.responseText;var Z=cd5(y);if(Z){g.CU(v.player,"onHeartbeat",Z);var J=Z.status==="ok"?Z.stop_heartbeat?2:0:Z.status==="stop"?1:Z.status==="live_stream_offline"?0:-1}else J=(J=y.match(zYr))?J[1]==="0"?0:1:-1;de5(v,void 0,Z,y,J)}},
onError:y=>{Nt(v)&&I2(v,!0,`net-${y.status}`)},
onTimeout:()=>{Nt(v)&&I2(v,!0,"timeout")},
withCredentials:!0})},Nt=function(v){var q=v.getVideoData();
return v.player.getPresentingPlayerType()===3||!v.player.J().experiments.fk().D.yY(g.u5x)&&v.player.getPlayerStateObject(v.getPlayerType()).D(4)?!1:Wc(v)||q.isLivePlayback?!0:(St(v),!1)},tk_=function(v,q,x){if(v.heartbeatParams?.url){var X=g.md(v.heartbeatParams.url,{request_id:g.i_()});
x.Y&&(X=g.md(X,{vvt:x.Y}),x.mdxEnvironment&&(X=g.md(X,{mdx_environment:x.mdxEnvironment})));g.U2(q,x.oauthToken).then(y=>{y&&(X=g.md(X,{access_token:y}));H0r(v,x,X)})}},QGs=async function(v,q,x){var X={videoId:x.videoId,
sequenceNumber:v.sequenceNumber,heartbeatServerData:x.N("html5_use_reloaded_heartbeat_server_data")?x.heartbeatServerData:v.hk??x.heartbeatServerData};v.G=v.attestationResponse;x.Wy&&(X.attestationResponse=await v.G);var y=g.iR(x),Z=y.client??{};Z.utcOffsetMinutes=v.utcOffsetMinutes;X.context=y;X.cpn=x.clientPlaybackNonce;if(y=typeof Intl!=="undefined"?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)Z.timeZone=y;Z={heartbeatChecks:[]};if(y=x.getPlayerResponse())x.heartbeatToken&&(X.heartbeatToken=
x.heartbeatToken),(y=y.playabilityStatus)&&(y=y.liveStreamability)&&y.liveStreamabilityRenderer&&Z.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");x.heartbeatToken&&Z.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");if(g.cT(q)){Z.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED");var J=KuT(v);y={};J!==null&&(y.clientPlayerPositionUtcMillis=J);J=v.player.e2()?.W4()?.gz()||0;J>0&&(y.freePreviewWatchedDuration={seconds:`${J}`});Z.unpluggedParams=y}X.heartbeatRequestParams=Z;x.isLivePlayback?
(Z=KuT(v),Z!==null&&(X.playbackState||(X.playbackState={}),X.playbackState.playbackPosition={utcTimeMillis:Z})):q.N("enable_heartbeat_vod_playback_position")&&(Z=O0r(v),Z!==null&&(X.playbackState||(X.playbackState={}),X.playbackState.playbackPosition={streamTimeMillis:Z}));v.player.X3("heartbeatRequest",X);var M={timeout:3E4,onSuccess:l=>{if(!v.X.isActive()&&Nt(v)){var B=v.getVideoData(),a=B.Wy&&v.G==null;B.Wy=!!l.heartbeatAttestationConfig?.requiresAttestation||a;a=l.playabilityStatus;var S=JSON.stringify(a)||
"{}";l.authenticationMismatch&&v.player.W("authshear",{});var I=-1;var b=l.playabilityStatus;b&&(g.CU(v.player,"onHeartbeat",b),b.status==="OK"?I=l.stopHeartbeat?2:0:b.status==="UNPLAYABLE"?I=1:b.status==="LIVE_STREAM_OFFLINE"&&(I=0));v.sequenceNumber&&I===-1||v.L.reset();v.sequenceNumber++;!B.N("html5_use_reloaded_heartbeat_server_data")&&l.heartbeatServerData&&(v.hk=l.heartbeatServerData);B.Sp=l;(b=l.playerCueRangeSet)&&g.OM(B,b);l.playerCueRanges&&l.playerCueRanges.length>0&&(B.cueRanges=l.playerCueRanges);
l.progressBarConfig?.progressBarStartPosition&&l.progressBarConfig?.progressBarEndPosition&&(B.progressBarStartPosition=l.progressBarConfig.progressBarStartPosition,B.progressBarEndPosition=l.progressBarConfig.progressBarEndPosition);B.compositeLiveIngestionOffsetToken=l.compositeLiveIngestionOffsetToken;l.compositeLiveStatusToken!==B.compositeLiveStatusToken&&(B.compositeLiveStatusToken=l.compositeLiveStatusToken);B.heartbeatLoggingToken=l.heartbeatLoggingToken;B.N("html5_use_reloaded_heartbeat_server_data")&&
l.heartbeatServerData&&(B.heartbeatServerData=l.heartbeatServerData);B.X3("dataupdated");de5(v,l,a,S,I)}},
onError:l=>{Nt(v)&&I2(v,!0,`net-${l.status}`)},
onTimeout:()=>{Nt(v)&&I2(v,!0,"timeout")}};
g.U2(q,g.Pn(x)).then(l=>{l&&(M.VT=`Bearer ${l}`);g.Uf(v.wO,"player/heartbeat",X,M)})},KuT=function(v){return(v=v.player.getProgressState(v.getPlayerType()).ingestionTime)&&isFinite(v)?`${Math.floor(v*1E3)}`:null},O0r=function(v){return(v=v.player.getCurrentTime({playerType:v.getPlayerType()}))&&isFinite(v)?`${Math.floor(v*1E3)}`:null},de5=function(v,q,x,X,y){y===-1?(x=`decode ${g.m5(X,3)}`,I2(v,!1,x)):y===2?(St(v),v.C=!0):(v.Y=0,v.X.stop(),y===1?(v.C=!1,x&&x.errorCode==="PLAYABILITY_ERROR_CODE_EMBARGOED"&&
v.player.J3(!0),y=`pe.${x?.errorCode};ps.${x?.status}`,v.player.KW("heartbeat.stop",2,v.HS(X),y,void 0,x?.errorScreen?.playerErrorMessageRenderer),g.PK("heartbeatActionPlayerHalted",$es(x)),q?.videoTransitionEndpoint&&x&&(q=q.videoTransitionEndpoint,(X=g.k(q,g.zU))&&rd2(v,X,x,{itct:q?.clickTrackingParams}))):(v.C=!0,X=0,v.j&&x&&(X=kwO(v,q,x),v.player.X3("livestatedata",x)),X?Bc(v,X):Bc(v)))},I2=function(v,q,x){if(!v.X.isActive()){v.X.stop();
v.Y++;var X=q?"heartbeat.net":"heartbeat.servererror";{let Z=v.getVideoData();if(Z.f9||q&&!g.wx(v.getVideoData())&&!Wc(v)&&Z.isLivePlayback)var y=!1;else v.heartbeatParams?.retries?y=v.heartbeatParams.retries:y=Z.rU||5,y=v.Y>=y}y?(g.PK("heartbeatActionPlayerHalted",q?{enforcedPolicyToHaltOnNetworkFailure:!0}:$es()),(q=v.getVideoData())&&q.isLivePlayback?v.player.KW(X,1,"\ub3d9\uc601\uc0c1 \uc7ac\uc0dd\uc774 \uc911\ub2e8\ub418\uc5c8\uc2b5\ub2c8\ub2e4. \ub2e4\uc2dc \uc2dc\ub3c4\ud574 \uc8fc\uc138\uc694.",
x):v.player.KW(X,1,"\ub3d9\uc601\uc0c1\uc5d0 \ub77c\uc774\uc120\uc2a4\ub97c \ubd80\uc5ec\ud558\ub294 \uc911\uc5d0 \uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4.",x)):(Bc(v,v.L.getValue()),g.Mg(v.L))}},$es=function(v){var q={enforcedPolicyToHaltOnNetworkFailure:!1};
v&&(q.serializedServerContext=v.additionalLoggingData);return q},mes=function(v,q){return(v=Number(v?.pollDelayMs))?v:(q=Number(q?.pollDelayMs))?q:0},rd2=function(v,q,x,X){var y=q&&q.videoId;
return y?(v.player.g7(y,{autonav:"1",...(X||{})},void 0,!0,!0,q,g.Pn(v.getVideoData())),a2("HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",x),!0):!1},a2=function(v,q){v={trigger:"HEARTBEAT_ACTION_TRIGGER_IMMEDIATE",
reason:v};q&&(v.serializedServerContext=q.additionalLoggingData);g.PK("heartbeatActionPlayerTransitioned",v)};
g.vz.prototype.OA=g.X7(13,function(v,q){this.app.OA(v,1,q)});
g.wj.prototype.OA=g.X7(12,function(v,q=1,x){this.LF({playerType:q}).tI(v,void 0,x)});
var bn={ERAS:["BC","AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y",
"MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5};
bn={ERAS:["BC","AD"],ERANAMES:["\uae30\uc6d0\uc804","\uc11c\uae30"],NARROWMONTHS:"1\uc6d4 2\uc6d4 3\uc6d4 4\uc6d4 5\uc6d4 6\uc6d4 7\uc6d4 8\uc6d4 9\uc6d4 10\uc6d4 11\uc6d4 12\uc6d4".split(" "),STANDALONENARROWMONTHS:"1\uc6d4 2\uc6d4 3\uc6d4 4\uc6d4 5\uc6d4 6\uc6d4 7\uc6d4 8\uc6d4 9\uc6d4 10\uc6d4 11\uc6d4 12\uc6d4".split(" "),MONTHS:"1\uc6d4 2\uc6d4 3\uc6d4 4\uc6d4 5\uc6d4 6\uc6d4 7\uc6d4 8\uc6d4 9\uc6d4 10\uc6d4 11\uc6d4 12\uc6d4".split(" "),STANDALONEMONTHS:"1\uc6d4 2\uc6d4 3\uc6d4 4\uc6d4 5\uc6d4 6\uc6d4 7\uc6d4 8\uc6d4 9\uc6d4 10\uc6d4 11\uc6d4 12\uc6d4".split(" "),
SHORTMONTHS:"1\uc6d4 2\uc6d4 3\uc6d4 4\uc6d4 5\uc6d4 6\uc6d4 7\uc6d4 8\uc6d4 9\uc6d4 10\uc6d4 11\uc6d4 12\uc6d4".split(" "),STANDALONESHORTMONTHS:"1\uc6d4 2\uc6d4 3\uc6d4 4\uc6d4 5\uc6d4 6\uc6d4 7\uc6d4 8\uc6d4 9\uc6d4 10\uc6d4 11\uc6d4 12\uc6d4".split(" "),WEEKDAYS:"\uc77c\uc694\uc77c \uc6d4\uc694\uc77c \ud654\uc694\uc77c \uc218\uc694\uc77c \ubaa9\uc694\uc77c \uae08\uc694\uc77c \ud1a0\uc694\uc77c".split(" "),STANDALONEWEEKDAYS:"\uc77c\uc694\uc77c \uc6d4\uc694\uc77c \ud654\uc694\uc77c \uc218\uc694\uc77c \ubaa9\uc694\uc77c \uae08\uc694\uc77c \ud1a0\uc694\uc77c".split(" "),
SHORTWEEKDAYS:"\uc77c\uc6d4\ud654\uc218\ubaa9\uae08\ud1a0".split(""),STANDALONESHORTWEEKDAYS:"\uc77c\uc6d4\ud654\uc218\ubaa9\uae08\ud1a0".split(""),NARROWWEEKDAYS:"\uc77c\uc6d4\ud654\uc218\ubaa9\uae08\ud1a0".split(""),STANDALONENARROWWEEKDAYS:"\uc77c\uc6d4\ud654\uc218\ubaa9\uae08\ud1a0".split(""),SHORTQUARTERS:["1\ubd84\uae30","2\ubd84\uae30","3\ubd84\uae30","4\ubd84\uae30"],QUARTERS:["\uc81c 1/4\ubd84\uae30","\uc81c 2/4\ubd84\uae30","\uc81c 3/4\ubd84\uae30","\uc81c 4/4\ubd84\uae30"],AMPMS:["\uc624\uc804",
"\uc624\ud6c4"],DATEFORMATS:["y\ub144 MMMM d\uc77c EEEE","y\ub144 MMMM d\uc77c","y. M. d.","yy. M. d."],TIMEFORMATS:["a h\uc2dc m\ubd84 s\ucd08 zzzz","a h\uc2dc m\ubd84 s\ucd08 z","a h:mm:ss","a h:mm"],DATETIMEFORMATS:["{1} {0}","{1} {0}","{1} {0}","{1} {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5};
var Deg=["ATTESTATION_ERROR_UNKNOWN","ATTESTATION_ERROR_VM_NOT_INITIALIZED","ATTESTATION_ERROR_VM_NO_RESPONSE","ATTESTATION_ERROR_VM_TIMEOUT","ATTESTATION_ERROR_VM_INTERNAL_ERROR"],PeB={300:"STREAMING_DEVICES_QUOTA_PER_24H_EXCEEDED",301:"ALREADY_PINNED_ON_A_DEVICE",303:"STOPPED_BY_ANOTHER_PLAYBACK",304:"TOO_MANY_STREAMS_PER_USER",305:"TOO_MANY_STREAMS_PER_ENTITLEMENT",400:"VIDEO_NOT_FOUND",401:"GEO_FAILURE",402:"STREAMING_NOT_ALLOWED",403:"UNSUPPORTED_DEVICE",405:"VIDEO_FORBIDDEN",500:"PURCHASE_NOT_FOUND",
501:"RENTAL_EXPIRED",502:"PURCHASE_REFUNDED",5E3:"BAD_REQUEST",5001:"CGI_PARAMS_MISSING",5002:"CGI_PARAMS_MALFORMED",5100:"AUTHENTICATION_MISSING",5101:"AUTHENTICATION_MALFORMED",5102:"AUTHENTICATION_EXPIRED",5200:"CAST_TOKEN_MALFORMED",5201:"CAST_TOKEN_EXPIRED",5202:"CAST_TOKEN_FAILED",5203:"CAST_SESSION_VIDEO_MISMATCHED",5204:"CAST_SESSION_DEVICE_MISMATCHED",6E3:"INVALID_DRM_MESSAGE",7E3:"SERVER_ERROR",8E3:"RETRYABLE_ERROR"};g.n=ln.prototype;g.n.ED=bn.FIRSTDAYOFWEEK;g.n.aW=bn.FIRSTWEEKCUTOFFDAY;
g.n.clone=function(){var v=new ln(this.date);v.ED=this.ED;v.aW=this.aW;return v};
g.n.getFullYear=function(){return this.date.getFullYear()};
g.n.getYear=function(){return this.getFullYear()};
g.n.getMonth=function(){return this.date.getMonth()};
g.n.getDate=function(){return this.date.getDate()};
g.n.getTime=function(){return this.date.getTime()};
g.n.getDay=function(){return this.date.getDay()};
g.n.getUTCFullYear=function(){return this.date.getUTCFullYear()};
g.n.getUTCMonth=function(){return this.date.getUTCMonth()};
g.n.getUTCDate=function(){return this.date.getUTCDate()};
g.n.getUTCDay=function(){return this.date.getDay()};
g.n.getUTCHours=function(){return this.date.getUTCHours()};
g.n.getUTCMinutes=function(){return this.date.getUTCMinutes()};
g.n.getTimezoneOffset=function(){return this.date.getTimezoneOffset()};
g.n.set=function(v){this.date=new Date(v.getFullYear(),v.getMonth(),v.getDate())};
g.n.setFullYear=function(v){this.date.setFullYear(v)};
g.n.setYear=function(v){this.setFullYear(v)};
g.n.setMonth=function(v){this.date.setMonth(v)};
g.n.setDate=function(v){this.date.setDate(v)};
g.n.setTime=function(v){this.date.setTime(v)};
g.n.setUTCFullYear=function(v){this.date.setUTCFullYear(v)};
g.n.setUTCMonth=function(v){this.date.setUTCMonth(v)};
g.n.setUTCDate=function(v){this.date.setUTCDate(v)};
g.n.add=function(v){if(v.years||v.months){var q=this.getMonth()+v.months+v.years*12,x=this.getYear()+Math.floor(q/12);q%=12;q<0&&(q+=12);a:{switch(q){case 1:var X=x%4!=0||x%100==0&&x%400!=0?28:29;break a;case 5:case 8:case 10:case 3:X=30;break a}X=31}X=Math.min(X,this.getDate());this.setDate(1);this.setFullYear(x);this.setMonth(q);this.setDate(X)}v.days&&(x=this.getYear(),q=x>=0&&x<=99?-1900:0,v=new Date((new Date(x,this.getMonth(),this.getDate(),12)).getTime()+v.days*864E5),this.setDate(1),this.setFullYear(v.getFullYear()+
q),this.setMonth(v.getMonth()),this.setDate(v.getDate()),Mt(this,v.getDate()))};
g.n.equals=function(v){return!(!v||this.getYear()!=v.getYear()||this.getMonth()!=v.getMonth()||this.getDate()!=v.getDate())};
g.n.toString=function(){var v=this.getFullYear(),q=v<0?"-":v>=1E4?"+":"";return[q+jt(Math.abs(v),q?6:4),jt(this.getMonth()+1,2),jt(this.getDate(),2)].join("")+""};
g.n.valueOf=function(){return this.date.valueOf()};var Wus=new g.Ju("addUpcomingEventReminderEndpoint");var IJs=new g.Ju("removeUpcomingEventReminderEndpoint");var TB5=class extends g.gu{constructor(v){super({A:"div",Im:[{A:"button",KF:["ytp-offline-slate-button","ytp-button"],Im:[{A:"div",dO:"ytp-offline-slate-button-icon",am:"{{icon}}"},{A:"div",dO:"ytp-offline-slate-button-text",am:"{{text}}"}]}]});this.U=v;this.D=this.toggleButtonRenderer=null;(this.O=this.tk("ytp-offline-slate-button"))&&this.D3(this.O,"click",this.C);this.hide()}C(){if(this.toggleButtonRenderer){let v=this.toggleButtonRenderer;v.isToggled?pYs(this,v.toggledServiceEndpoint):pYs(this,
v.defaultServiceEndpoint);v.isToggled=!v.isToggled;GG(this)}}};var UeT=class extends g.gu{constructor(v){super({A:"div",dO:"ytp-offline-slate",Im:[{A:"div",dO:"ytp-offline-slate-background"},{A:"div",dO:"ytp-offline-slate-bar",Im:[{A:"span",dO:"ytp-offline-slate-icon",Im:[{A:"svg",N4:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},Im:[{A:"path",N4:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{A:"circle",N4:{cx:"12",cy:"12",r:"3"}}]}]},{A:"span",dO:"ytp-offline-slate-messages",Im:[{A:"div",dO:"ytp-offline-slate-main-text",N4:{"aria-label":"{{label}}"},am:"{{mainText}}"},{A:"div",dO:"ytp-offline-slate-subtitle-text",am:"{{subtitleText}}"}]},{A:"span",dO:"ytp-offline-slate-buttons"}]},{A:"button",KF:["ytp-offline-slate-close-button","ytp-button"],Im:[g.PI()]},{A:"button",KF:["ytp-offline-slate-open-button","ytp-button"],Im:[g.$o()]}]});this.api=v;this.D=this.O=null;this.background=this.tk("ytp-offline-slate-background");
this.C=this.tk("ytp-offline-slate-bar");this.K=new g.YA(()=>{g.hy(this.C,"ytp-offline-slate-bar-fade")},15E3);
this.Y=!1;this.L=new g.YA(()=>{g.hy(this.element,"ytp-offline-slate-collapsed")},15E3);
g.r(this,this.L);g.r(this,this.K);this.countdownTimer=new g.YA(this.G,1E3,this);this.D3(v,"presentingplayerstatechange",this.V);this.D3(v,"livestatedata",this.y0);this.D3(this.tk("ytp-offline-slate-close-button"),"click",()=>{g.hy(this.element,"ytp-offline-slate-collapsed")});
this.D3(this.tk("ytp-offline-slate-open-button"),"click",()=>{g.U6(this.element,"ytp-offline-slate-collapsed")});
this.hide();v=this.getVideoData();v.getPlayerResponse()&&(v=v.getPlayerResponse().playabilityStatus)&&this.y0(v);v=this.api.getPresentingPlayerType()===8&&!this.getVideoData().NB;var q=this.api.getPresentingPlayerType()===8;g.m0(this.element,"ytp-offline-slate-premiere-trailer",v);g.m0(this.element,"ytp-offline-slate-hide-background",q)}getPlayerType(){if(this.api.getPresentingPlayerType()===8)return 1}getVideoData(){return this.api.getVideoData({playerType:this.getPlayerType()})}y0(v){var q=v?.liveStreamability?.liveStreamabilityRenderer?.offlineSlate;
if(q){this.O=v;q=q.liveStreamOfflineSlateRenderer;q.canShowCountdown?this.G():A_(this,q);var x=v?.liveStreamability?.liveStreamabilityRenderer?.offlineSlate?.liveStreamOfflineSlateRenderer?.thumbnail;if(x){let X=0,y=null;x=x.thumbnails;for(let Z=0;Z<x.length;Z++)x[Z].width>X&&(X=x[Z].width||0,y=x[Z].url);y&&(this.background.style.backgroundImage=`url(${y})`)}else this.background.style.backgroundImage="";q.actionButtons?(this.D||(this.D=new TB5(this.api),this.D.om(this.tk("ytp-offline-slate-buttons")),
g.r(this,this.D)),So6(this.D,q.actionButtons&&q.actionButtons[0])):this.D&&So6(this.D,null);this.O=v}else this.O=null;this.V()}V(v){if(this.api.getPresentingPlayerType()===8)var q=!0;else{var x=this.api.getPlayerStateObject(),X=this.getVideoData();q=X.isLivePlayback&&(x.isBuffering()||x.D(2)||x.D(64));var y=X.autonavState===2&&x.D(2);x=x.isPlaying()&&!g.fy(X)&&!this.api.isAtLiveHead(void 0,!0);q=q&&!x&&!y}q&&this.O?this.X?v?.I8(2)&&!this.getVideoData().NB&&(g.U6(this.element,"ytp-offline-slate-collapsed"),
this.L.stop(),g.U6(this.C,"ytp-offline-slate-bar-fade"),this.K.start()):(this.show(),this.L.start(),this.api.X3("offlineslatestatechange"),this.Y&&this.api.OA()):this.X&&(this.hide(),this.api.X3("offlineslatestatechange"))}G(){var v=this.O?.liveStreamability?.liveStreamabilityRenderer?.offlineSlate?.liveStreamOfflineSlateRenderer;if(v){var q=Math.floor(g.QT()/1E3),x=v.canShowCountdown&&Number(v.scheduledStartTime);!x||x<=q?(A_(this,v),this.countdownTimer.stop()):(q=g.Rs(x-q),A_(this,v,q),g.cr(this.countdownTimer))}}QY(){this.countdownTimer.dispose();
this.countdownTimer=null;super.QY()}};var fJs=class{constructor(v,q){var x=(0,g.O)();this.module="heartbeat";this.trigger=v;this.D=q;this.O=x}X(v){return this.trigger&&v.trigger?this.module===v.module&&this.trigger===v.trigger&&this.D===v.D:!1}isExpired(){return(0,g.O)()-this.O>6E4}toString(){return`${this.module}:${this.trigger}:${this.D}`}};var zYr=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.wR("heartbeat",class extends g.bG{constructor(v){super(v);this.K=!1;this.Y=0;this.C=!1;this.X=new g.YA(()=>{wYs(this)},0);
this.D=this.heartbeatParams=null;this.j=!1;this.L=new g.j5(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.wO=new g.$M(void 0);this.attestationResponse=Promise.resolve(void 0);this.G=Promise.resolve(void 0);this.utcOffsetMinutes=-(new ln).getTimezoneOffset();this.O=new g.zy(this);g.r(this,this.X);g.r(this,this.O);VkO(this);naT(this);this.O.D3(v,"heartbeatparams",this.DI);this.O.D3(v,"presentingplayerstatechange",this.Oy);this.O.D3(v,"videoplayerreset",this.V);this.O.D3(v,g.vh("heartbeat"),
this.onCueRangeEnter);this.j&&this.D&&kwO(this,void 0,this.D);var q=new g.q_(1E3,0x7ffffffffffff,{priority:1,namespace:"heartbeat"}),x=new g.q_(0x8000000000000,0x8000000000000,{id:"stream_end",priority:1,namespace:"heartbeat"});v.gN([q,x]);RYO(this)}QY(){St(this);this.player.KK("heartbeat");super.QY()}onCueRangeEnter(){var v=this.getVideoData();this.K=!0;v.N("html5_use_server_init_heartbeat_delay")?(v=CG(this),isNaN(v)||Bc(this,v)):Bc(this,2E3)}DI(v){var q=this.getVideoData();this.heartbeatParams=
v;q.N("html5_use_server_init_heartbeat_delay")?(v=CG(this),isNaN(v)||Bc(this,v)):Bc(this,2E3)}Oy(v){if(this.player.getPresentingPlayerType()!==8&&this.D?.status!=="UNPLAYABLE")if(v.state.D(2)||v.state.D(64))St(this),this.j&&(this.K=!0,this.getVideoData().N("html5_use_server_init_heartbeat_delay")?(v=CG(this),isNaN(v)||Bc(this,v)):Bc(this,1E3));else{let q=this.player.J().experiments.fk().D.yY(g.u5x);(v.state.D(1)||v.state.D(8)||q&&v.state.D(4))&&Bc(this,CG(this))}}V(){this.player.getPresentingPlayerType()!==
3&&Bc(this,CG(this))}getPlayerType(){if(this.player.getPresentingPlayerType()===8)return 1}getVideoData(){return this.player.getVideoData({playerType:this.getPlayerType()})}Eo(v){switch(v){case 4:case 3:return!1}return!0}HS(v){var q="LICENSE",x=cd5(v);if(x)return x.reason||g.Lp[q]||"";if(v=v.match(zYr))if(v=Number(v[1]))q=(q=PeB[v.toString()])?q:"LICENSE";return g.Lp[q]||""}jM(){return!!this.offlineSlate&&this.offlineSlate.X}});})(_yt_player);
